name: OTA Update

# Disabled until app is published to stores — no production builds exist yet.
# Uncomment the 'on' block below when ready.
# on:
#   push:
#     branches: ['main']
#     paths:
#       - 'apps/mobile/**'

jobs:
  fingerprint:
    type: fingerprint

  get-ios-build:
    name: Check existing iOS build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: production

  get-android-build:
    name: Check existing Android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: production

  update:
    name: Publish OTA update
    type: update
    needs: [get-ios-build, get-android-build]
    if: ${{ needs["get-ios-build"].outputs.build_id && needs["get-android-build"].outputs.build_id }}
    params:
      branch: production
      platform: all
      message: OTA update from ${{ github.sha }}

  notify-ota:
    type: doc
    needs: [update]
    params:
      md: |
        ## OTA Update Published
        Branch: `production`
        Commit: `${{ github.sha }}`

  needs-native-build:
    type: doc
    needs: [get-ios-build, get-android-build]
    if: ${{ !needs["get-ios-build"].outputs.build_id || !needs["get-android-build"].outputs.build_id }}
    params:
      md: |
        ## Native Changes Detected
        No matching production build found for one or both platforms.
        Run the **Production Release** workflow manually to create new native builds.
