name: Production Release

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - all
          - ios
          - android
        default: all
        required: true
      message:
        type: string
        required: false

jobs:
  build-ios:
    type: build
    if: ${{ inputs.platform == 'all' || inputs.platform == 'ios' }}
    params:
      platform: ios
      profile: production
      message: ${{ inputs.message || 'Production release' }}

  build-android:
    type: build
    if: ${{ inputs.platform == 'all' || inputs.platform == 'android' }}
    params:
      platform: android
      profile: production
      message: ${{ inputs.message || 'Production release' }}

  approve-release:
    type: require-approval
    needs:
      - build-ios
      - build-android

  submit-ios:
    type: submit
    needs: [approve-release]
    if: ${{ inputs.platform == 'all' || inputs.platform == 'ios' }}
    params:
      build_id: ${{ needs["build-ios"].outputs.build_id }}
      profile: production

  submit-android:
    type: submit
    needs: [approve-release]
    if: ${{ inputs.platform == 'all' || inputs.platform == 'android' }}
    params:
      build_id: ${{ needs["build-android"].outputs.build_id }}
      profile: production
