name: Test

on:
  push:
    branches: ['main']
    paths:
      - 'apps/mobile/**'
      - 'packages/**'
  pull_request:
    paths:
      - 'apps/mobile/**'
      - 'packages/**'

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

defaults:
  tools:
    node: '20'
    pnpm: '10'

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: TypeScript check
        run: pnpm --filter @parking-ticket-pal/mobile check-types
      - name: Lint
        run: pnpm --filter @parking-ticket-pal/mobile lint

  unit-tests:
    name: Unit Tests
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Run tests
        run: pnpm --filter @parking-ticket-pal/mobile test --ci --watchAll=false

  build-e2e-android:
    name: Build Android for E2E
    needs: [lint-and-typecheck, unit-tests]
    type: build
    params:
      platform: android
      profile: e2e-test

  build-e2e-ios:
    name: Build iOS for E2E
    needs: [lint-and-typecheck, unit-tests]
    type: build
    params:
      platform: ios
      profile: e2e-test

  e2e-android:
    name: E2E Tests (Android)
    needs: [build-e2e-android]
    type: maestro
    params:
      build_id: ${{ needs["build-e2e-android"].outputs.build_id }}
      flow_path: .maestro/
      retries: 2

  e2e-ios:
    name: E2E Tests (iOS)
    needs: [build-e2e-ios]
    type: maestro
    params:
      build_id: ${{ needs["build-e2e-ios"].outputs.build_id }}
      flow_path: .maestro/
      retries: 2

  comment:
    name: Post Results
    type: github-comment
    if: ${{ github.event_name == 'pull_request' }}
    after: [e2e-android, e2e-ios]
    params:
      message: |
        **Test results for PR #${{ github.event.pull_request.number }}**

        | Job | Status |
        |-----|--------|
        | Lint & Typecheck | ${{ needs["lint-and-typecheck"].status || 'passed' }} |
        | Unit Tests | ${{ needs["unit-tests"].status || 'passed' }} |
        | E2E Android | ${{ after["e2e-android"].status }} |
        | E2E iOS | ${{ after["e2e-ios"].status }} |
