export const COUNCIL_TOPICS = [
  // Tier 1: Major Cities & London Boroughs (High Priority)
  'Westminster Council parking enforcement',
  'Camden Council PCN appeals',
  'Islington parking permits and restrictions',
  'Kensington and Chelsea parking zones',
  'Lambeth Council parking fines',
  'Southwark parking enforcement',
  'Tower Hamlets parking permits',
  'Hackney Council parking bays',
  'Wandsworth parking restrictions',
  'Hammersmith and Fulham parking',
  'Birmingham City Council parking fines',
  'Manchester City Council parking enforcement',
  'Leeds City Council PCN appeals',
  'Glasgow City Council parking',
  'Edinburgh Council parking zones',
  'Liverpool City Council parking',
  'Bristol City Council parking permits',
  'Sheffield Council parking enforcement',
  'Newcastle City Council parking',
  'Cardiff Council parking fines',

  // Tier 2: Other London Boroughs
  // 'Barnet Council parking enforcement',
  // 'Brent Council parking permits',
  // 'Bromley Council PCN appeals',
  // 'Croydon Council parking zones',
  // 'Ealing Council parking restrictions',
  // 'Enfield Council parking fines',
  // 'Greenwich Council parking',
  // 'Haringey Council parking enforcement',
  // 'Harrow Council parking permits',
  // 'Hounslow Council parking',
  // 'Kingston Council parking zones',
  // 'Lewisham Council parking fines',
  // 'Merton Council parking enforcement',
  // 'Newham Council parking',
  // 'Redbridge Council parking permits',
  // 'Richmond Council parking restrictions',
  // 'Sutton Council parking',
  // 'Waltham Forest parking enforcement',

  // Tier 3: Major Towns & Cities (100k+ population)
  // 'Nottingham City Council parking',
  // 'Leicester City Council parking',
  // 'Coventry City Council parking',
  // 'Brighton and Hove parking enforcement',
  // 'Plymouth City Council parking',
  // 'Southampton City Council parking',
  // 'Reading Borough Council parking',
  // 'Derby City Council parking',
  // 'Stoke-on-Trent parking',
  // 'Wolverhampton Council parking',
  // 'Aberdeen City Council parking',
  // 'Portsmouth City Council parking',
  // 'Northampton Council parking',
  // 'Luton Borough Council parking',
  // 'Bolton Council parking enforcement',
  // 'Bournemouth Council parking',
  // 'Norwich City Council parking',
  // 'Swindon Borough Council parking',
  // 'Milton Keynes Council parking',
  // 'Warrington Borough Council parking',
  // 'Huddersfield Council parking',
  // 'Oxford City Council parking',
  // 'Cambridge City Council parking',
  // 'York City Council parking',
  // 'Bath and North East Somerset parking',

  // Tier 4: Counties & Unitary Authorities
  // 'Kent County Council parking',
  // 'Essex County Council parking',
  // 'Surrey County Council parking',
  // 'Hampshire County Council parking',
  // 'Lancashire County Council parking',
  // 'North Yorkshire parking enforcement',
  // 'Durham County Council parking',
  // 'Cornwall Council parking',
  // 'Devon County Council parking',
  // 'Dorset Council parking',

  // Special Categories (High search volume despite size)
  // 'Stratford-upon-Avon parking', // Tourist area
  // 'Windsor and Maidenhead parking', // Tourist area
  // 'Canterbury City Council parking', // Tourist/historic
  // 'Chester parking enforcement', // Tourist/historic
  // 'Blackpool Council parking', // Tourist area
  // 'Scarborough Borough Council parking', // Tourist area
  // 'Lake District parking enforcement', // Tourist area
  // 'Cotswolds District Council parking', // Tourist area
];

export const BLOG_TOPICS = [
  // On-Street Parking Contraventions (01-49)
  'PCN code 01 parked in restricted street',
  'PCN code 02 loading in restricted street',
  'PCN code 04 parked in meter bay without payment',
  'PCN code 05 parked after meter expired',
  'PCN code 06 parked without clear display of ticket',
  'PCN code 07 parked with payment less than required',
  'PCN code 08 parked beyond maximum stay at meter',
  'PCN code 09 parked without payment of parking charge',
  'PCN code 10 parked without clearly displaying two tickets',
  'PCN code 11 parked without payment in pay and display',
  'PCN code 12 parked in residents place without permit',
  'PCN code 14 parked in electric vehicle charging place',
  'PCN code 16 parked in permit space without displaying permit',
  'PCN code 17 parked in permit bay without valid permit',
  'PCN code 18 parked in shared use bay without payment',
  'PCN code 19 parked in residents bay with invalid permit',
  'PCN code 20 parked in loading gap marked by yellow line',
  'PCN code 21 parked in suspended bay',
  'PCN code 22 re-parked in same place within one hour',
  'PCN code 23 parked in place not designated for that class',
  'PCN code 24 not parked correctly within markings',
  'PCN code 25 parked in loading place during restricted hours',
  'PCN code 26 parked in special enforcement area double parking',
  'PCN code 27 parked adjacent to dropped footway',
  'PCN code 28 parked in special enforcement area blocking',
  'PCN code 30 parked longer than permitted',
  'PCN code 40 parked in disabled bay without badge',
  'PCN code 41 parked in disabled bay beyond time limit',
  'PCN code 42 parked in police bay',
  'PCN code 43 parked in diplomatic vehicle bay',
  'PCN code 44 parked in marked ambulance bay',
  'PCN code 45 parked on taxi rank',
  'PCN code 46 parked in marked doctor bay',
  'PCN code 47 parked on restricted bus stop',
  'PCN code 48 parked in restricted school area',
  'PCN code 49 parked on cycle track or lane',
  'PCN code 99 parked on pedestrian crossing',

  // Higher-Level Off-Street Contraventions (70-96)
  'PCN code 70 parked in loading area off-street',
  'PCN code 71 parked in electric vehicle bay off-street',
  'PCN code 73 parked without payment in off-street car park',
  'PCN code 74 using vehicle in off-street restricted area',
  'PCN code 80 parked longer than maximum period off-street',
  'PCN code 81 parked in restricted area in car park',
  'PCN code 82 parked after expiry of paid time off-street',
  'PCN code 83 parked without clear display in off-street',
  'PCN code 84 parked with insufficient payment off-street',
  'PCN code 85 parked in permit bay without permit off-street',
  'PCN code 86 not parked correctly within bay markings off-street',
  'PCN code 87 parked in disabled bay without badge off-street',
  'PCN code 89 parked in car park when closed',
  'PCN code 90 re-parked within no return period off-street',
  'PCN code 91 parked in off-street car park without permit',
  'PCN code 92 parked exceeding maximum weight or height',
  'PCN code 93 parked in car share bay without permit',
  'PCN code 94 parked in marked bay for other vehicles',
  'PCN code 95 parked in parking place for another class',
  'PCN code 96 parked using altered or false Blue Badge',

  // Moving Traffic Contraventions (31-38, 50-52)
  'PCN code 31 entering box junction when prohibited',
  'PCN code 32 failing to give way to oncoming traffic',
  'PCN code 33 illegal U-turn',
  'PCN code 34 being in bus lane',
  'PCN code 35 failing to comply with no entry sign',
  'PCN code 36 failing to comply with no left turn',
  'PCN code 37 failing to comply with no right turn',
  'PCN code 38 failing to comply with straight ahead only',
  'PCN code 50 performing prohibited turn',
  'PCN code 51 failing to comply with priority signs',
  'PCN code 52 entering restricted area',

  // London-Specific Codes (Some variations)
  'PCN code 13 parked in suspended bay London',
  'PCN code 15 parked in residents bay using invalid permit',
  'PCN code 28a parked adjacent to school entrance markings',
  'PCN code 28b double parked on London red route',

  // Moving Traffic Violations
  'box junction enforcement rules',
  'no entry sign violations',
  'prohibited turn penalties',
  'bus lane PCN appeals',
  'one way street contraventions',
  'yellow box junction rules explained',
  'mandatory cycle lane violations',
  'no U-turn enforcement',
  'weight restriction violations',
  'width restriction penalties',

  // London-Specific
  'TfL bus lane cameras locations',
  'ULEZ expansion boundaries 2024',
  'ULEZ camera mistakes',
  'congestion charge autopay errors',
  'LEZ penalty charges',
  'red route parking rules',
  'Westminster parking zones',
  'Camden parking enforcement',
  'Islington CPZ rules',
  'City of London parking',

  // Private Parking Companies
  'ParkingEye appeal success',
  'Euro Car Parks tactics',
  'UKPC parking charges',
  'Smart Parking appeals',
  'ANPR camera errors',
  'private land parking rights',
  'supermarket parking fines',
  'hospital parking penalties',
  'retail park enforcement',
  'gym parking charges',

  // Appeals & Legal Process
  'informal PCN appeal template',
  'formal representations guide',
  'Traffic Penalty Tribunal process',
  'London Tribunals PATAS',
  'witness statement PE2 PE3',
  'statutory declaration TE9 TE7',
  'out of time statutory declaration',
  'compelling reasons for late appeal',
  'POPLA appeals process',
  'IAS independent appeals',

  // Enforcement & Debt Recovery
  'bailiff warrant of control',
  'enforcement agent fees explained',
  'vulnerable person bailiff rules',
  'controlled goods agreement',
  'bailiff complaint procedure',
  'council tax and parking debt',
  'foreign registered vehicle enforcement',
  'persistent evader database',
  'vehicle clamping laws',
  'DVLA keeper liability',

  // Special Circumstances
  'blue badge misuse penalties',
  'blue badge holder rights',
  'disabled parking bay abuse',
  'loading and unloading rules',
  'trader permits and exemptions',
  'wedding car parking rules',
  'breakdown parking defense',
  'emergency vehicle exemptions',
  'diplomatic immunity parking',
  'rental car parking fines',

  // Seasonal & Temporary
  'Christmas parking restrictions',
  'bank holiday enforcement',
  'match day parking zones',
  'event day restrictions',
  'suspended bay compensation',
  'roadworks parking rules',
  'market day restrictions',
  'street cleaning suspensions',

  // Residential & Permits
  'residents parking permit rules',
  'visitor permit regulations',
  'business parking permits',
  'doctors parking permits',
  'carers parking badges',
  'motorcycle parking bays',
  'electric vehicle charging bays',
  'car club parking spaces',

  // Common Issues & Mistakes
  'parking sign unclear defense',
  'pay and display machine broken',
  'PayByPhone app errors',
  'RingGo payment problems',
  'incorrect VRM entry',
  'cloned number plate PCN',
  'stolen vehicle parking fine',
  'sold vehicle fine received',

  // Specific Locations & Markings
  'school keep clear zigzag lines',
  'hospital emergency bay rules',
  'taxi rank operating hours',
  'coach parking restrictions',
  'motorcycle parking rules',
  'pavement parking laws',
  'grass verge parking rules',
  'private road parking rights',

  // Payment & Admin
  'PCN discount period rules',
  'payment plan arrangements',
  'hardship applications',
  'refund request process',
  'duplicate payment recovery',
  'company vehicle nominations',
  'hire car liability transfer',

  // Recent Changes & Updates
  'parking enforcement changes 2024',
  'new highway code rules',
  'pavement parking ban updates',
  'private parking code of practice',
  'BPA vs IPC membership',
  'grace period regulations',
  'consideration period rules',

  // Regional Variations
  'Scotland parking regulations',
  'Wales parking enforcement',
  'Northern Ireland PCN rules',
  'Manchester CAZ charges',
  'Birmingham CAZ enforcement',
  'Bristol clean air zone',

  // Technology & Systems
  'ANPR camera accuracy',
  'virtual parking permits',
  'cashless parking problems',
  'parking app comparison',
  'digital PCN appeals',
  'online tribunal hearings',

  // Prevention & Best Practice
  'avoiding parking fines guide',
  'understanding parking signs',
  'photographic evidence tips',
  'appeal letter templates',
  'keeping parking records',
  'dashcam evidence for appeals',
];

export const BLOG_TAGS = [
  'Residents Parking Permits',
  'UK Parking Regulations',
  'Council Parking Permits',
  'Traffic Enforcement Centre Appeals',
  'PCN Appeal Process UK',
  'Challenge Parking Fines UK',
  'Bailiffs',
  'Parking Debts',
  'UK Parking Enforcement',
  'Council Parking Enforcement',
  'UK Parking Fines',
  'Council Parking Regulations',
  'UK Parking Rules',
  'Penalty Charge Notices',
  'Box Junctions',
  'UK Traffic Fines',
  'Driving Penalties',
  'Appeals',
  'Legal Tips',
  'Appeal Failures',
  'Common Mistakes',
  'What Not To Do',
  'PCN',
  'TfL',
  'ULEZ',
  'Congestion Charge',
  'Blue Badge',
  'Disabled Parking',
  'Double Yellow Lines',
  'Loading Bays',
  'Bus Lanes',
  'School Keep Clear',
  'Moving Traffic',
  'PE3 Form',
  'TE9 Form',
  'TE7 Form',
  'PE2 Form',
  'Christmas Parking',
  'Contravention Codes',
  ...COUNCIL_TOPICS,
];

export const AUTHORS = [
  {
    name: 'Sarah Mitchell',
    title: 'Parking Rights Advocate',
    avatar: '/images/blog/authors/sarah-mitchell.png',
  },
  {
    name: 'James Wilson',
    title: 'Legal Counsel',
    avatar: '/images/blog/authors/james-wilson.png',
  },
  {
    name: 'Emma Thompson',
    title: 'Traffic Law Specialist',
    avatar: '/images/blog/authors/emma-thompson.png',
  },
  {
    name: 'David Chen',
    title: 'Consumer Rights Expert',
    avatar: '/images/blog/authors/david-chen.png',
  },
  {
    name: 'Lisa Rodriguez',
    title: 'Automotive Journalist',
    avatar: '/images/blog/authors/lisa-rodriguez.png',
  },
  {
    name: 'Amara Okafor',
    title: 'Council Liaison Officer',
    avatar: '/images/blog/authors/amara-okafor.png',
  },
  {
    name: 'Raj Patel',
    title: 'Transport Policy Analyst',
    avatar: '/images/blog/authors/raj-patel.png',
  },
  {
    name: 'Sophie Dubois',
    title: 'Traffic Law Specialist',
    avatar: '/images/blog/authors/sophie-dubois.png',
  },
  {
    name: 'Mohammed Al-Hassan',
    title: 'Appeals Tribunal Specialist',
    avatar: '/images/blog/authors/mohammed-al-hassan.png',
  },
  {
    name: "Grace O'Sullivan",
    title: 'Municipal Enforcement Expert',
    avatar: '/images/blog/authors/grace-osullivan.png',
  },
  {
    name: 'Kwame Asante',
    title: 'Community Rights Advisor',
    avatar: '/images/blog/authors/kwame-asante.png',
  },
  {
    name: 'Priya Sharma',
    title: 'Legal Aid Coordinator',
    avatar: '/images/blog/authors/priya-sharma.png',
  },
  {
    name: 'Oliver Johansson',
    title: 'Traffic Management Consultant',
    avatar: '/images/blog/authors/oliver-johansson.png',
  },
  {
    name: 'Fatima Benali',
    title: 'Dispute Resolution Specialist',
    avatar: '/images/blog/authors/fatima-benali.png',
  },
  {
    name: 'Marcus Campbell',
    title: 'Former Traffic Warden',
    avatar: '/images/blog/authors/marcus-campbell.png',
  },
  {
    name: 'Yuki Tanaka',
    title: 'Urban Planning Researcher',
    avatar: '/images/blog/authors/yuki-tanaka.png',
  },
  {
    name: 'Isabella Romano',
    title: 'Civil Enforcement Officer',
    avatar: '/images/blog/authors/isabella-romano.png',
  },
  {
    name: 'Tariq Khan',
    title: 'Bailiff Procedures Expert',
    avatar: '/images/blog/authors/tariq-khan.png',
  },
  {
    name: 'Hannah MacLeod',
    title: 'Traffic Law Specialist',
    avatar: '/images/blog/authors/hannah-macleod.png',
  },
  {
    name: 'Carlos Mendoza',
    title: 'Parking Technology Analyst',
    avatar: '/images/blog/authors/carlos-mendoza.png',
  },
];

export const PLACEHOLDER_AVATAR_IMAGE = '/images/blog/authors/placeholder.jpg';

export const PLACEHOLDER_BLOG_IMAGE = '/images/blog/placeholder.png';
