export const PRIVATE_COMPANY_IDS = [
  'horizon',
  'parkingEye',
  'euro-car-parks',
  'smart-parking',
  'apcoa-parking',
  'ncp',
  'q-park',
  'indigo-park',
  'excel-parking-services',
  'parking-control-management',
  'vehicle-control-services',
  'uk-parking-control',
  'civil-enforcement-ltd',
  'cp-plus',
  'saba-parking',
  'town-centre-parking',
  'britannia-parking',
  'gemini-parking-solutions',
  'athena-anpr',
  'alliance-parking-management',
  'premier-park',
  'one-parking',
  'g24',
  'ctl-parking',
  'highview-parking',
  'nationwide-parking-enforcement',
  'met-parking-services',
  'new-generation-parking',
  'park-watch',
  'armtrac',
  'swift-parking-services',
  'eagle-parking',
  'resolute-parking',
  'citrus-parking',
  'northern-parking-services',
  'flash-park',
  'parkmaven',
  'cambridgeshire-parking-enforcement',
  'council-responsible-parking',
  'patrol-parking',
  'all-parking-services',
  'apg-parking',
  'creative-car-park',
  'ace-parking',
  'zenith-parking',
  'link-parking',
  'moto-parking',
  'orbit-parking',
  'minster-baywatch',
  'north-west-parking-enforcement',
] as const;

export const TRANSPORT_AUTHORITY_IDS = ['tfl'] as const;

export const LOCAL_AUTHORITY_IDS = [
  'hartlepool',
  'middlesbrough',
  'redcar-and-cleveland',
  'stockton-on-tees',
  'darlington',
  'halton',
  'warrington',
  'blackburn-with-darwen',
  'blackpool',
  'kingston-upon-hull-city-of',
  'east-riding-of-yorkshire',
  'north-east-lincolnshire',
  'north-lincolnshire',
  'york',
  'derby',
  'leicester',
  'rutland',
  'nottingham',
  'herefordshire-county-of',
  'telford-and-wrekin',
  'stoke-on-trent',
  'bath-and-north-east-somerset',
  'bristol-city-of',
  'north-somerset',
  'south-gloucestershire',
  'plymouth',
  'torbay',
  'swindon',
  'peterborough',
  'luton',
  'southend-on-sea',
  'thurrock',
  'medway',
  'bracknell-forest',
  'west-berkshire',
  'reading',
  'slough',
  'windsor-and-maidenhead',
  'wokingham',
  'milton-keynes',
  'brighton-and-hove',
  'portsmouth',
  'southampton',
  'isle-of-wight',
  'county-durham',
  'cheshire-east',
  'cheshire-west-and-chester',
  'shropshire',
  'cornwall',
  'isles-of-scilly',
  'wiltshire',
  'bedford',
  'central-bedfordshire',
  'northumberland',
  'bournemouth-christchurch-and-poole',
  'dorset',
  'aylesbury-vale',
  'chiltern',
  'south-bucks',
  'wycombe',
  'cambridge',
  'east-cambridgeshire',
  'fenland',
  'huntingdonshire',
  'south-cambridgeshire',
  'allerdale',
  'barrow-in-furness',
  'carlisle',
  'copeland',
  'eden',
  'south-lakeland',
  'amber-valley',
  'bolsover',
  'chesterfield',
  'derbyshire-dales',
  'erewash',
  'high-peak',
  'north-east-derbyshire',
  'south-derbyshire',
  'east-devon',
  'exeter',
  'mid-devon',
  'north-devon',
  'south-hams',
  'teignbridge',
  'torridge',
  'west-devon',
  'eastbourne',
  'hastings',
  'lewes',
  'rother',
  'wealden',
  'basildon',
  'braintree',
  'brentwood',
  'castle-point',
  'chelmsford',
  'colchester',
  'epping-forest',
  'harlow',
  'maldon',
  'rochford',
  'tendring',
  'uttlesford',
  'cheltenham',
  'cotswold',
  'forest-of-dean',
  'gloucester',
  'stroud',
  'tewkesbury',
  'basingstoke-and-deane',
  'east-hampshire',
  'eastleigh',
  'fareham',
  'gosport',
  'hart',
  'havant',
  'new-forest',
  'rushmoor',
  'test-valley',
  'winchester',
  'broxbourne',
  'dacorum',
  'hertsmere',
  'north-hertfordshire',
  'three-rivers',
  'watford',
  'ashford',
  'canterbury',
  'dartford',
  'dover',
  'gravesham',
  'maidstone',
  'sevenoaks',
  'folkestone-and-hythe',
  'swale',
  'thanet',
  'tonbridge-and-malling',
  'tunbridge-wells',
  'burnley',
  'chorley',
  'fylde',
  'hyndburn',
  'lancaster',
  'pendle',
  'preston',
  'ribble-valley',
  'rossendale',
  'south-ribble',
  'west-lancashire',
  'wyre',
  'blaby',
  'charnwood',
  'harborough',
  'hinckley-and-bosworth',
  'melton',
  'north-west-leicestershire',
  'oadby-and-wigston',
  'boston',
  'east-lindsey',
  'lincoln',
  'north-kesteven',
  'south-holland',
  'south-kesteven',
  'west-lindsey',
  'breckland',
  'broadland',
  'great-yarmouth',
  'kings-lynn-and-west-norfolk',
  'north-norfolk',
  'norwich',
  'south-norfolk',
  'corby',
  'daventry',
  'east-northamptonshire',
  'kettering',
  'northampton',
  'south-northamptonshire',
  'wellingborough',
  'craven',
  'hambleton',
  'harrogate',
  'richmondshire',
  'ryedale',
  'scarborough',
  'selby',
  'ashfield',
  'bassetlaw',
  'broxtowe',
  'gedling',
  'mansfield',
  'newark-and-sherwood',
  'rushcliffe',
  'cherwell',
  'oxford',
  'south-oxfordshire',
  'vale-of-white-horse',
  'west-oxfordshire',
  'mendip',
  'sedgemoor',
  'south-somerset',
  'cannock-chase',
  'east-staffordshire',
  'lichfield',
  'newcastle-under-lyme',
  'south-staffordshire',
  'stafford',
  'staffordshire-moorlands',
  'tamworth',
  'babergh',
  'ipswich',
  'mid-suffolk',
  'elmbridge',
  'epsom-and-ewell',
  'guildford',
  'mole-valley',
  'reigate-and-banstead',
  'runnymede',
  'spelthorne',
  'surrey-heath',
  'tandridge',
  'waverley',
  'woking',
  'north-warwickshire',
  'nuneaton-and-bedworth',
  'rugby',
  'stratford-on-avon',
  'warwick',
  'adur',
  'arun',
  'chichester',
  'crawley',
  'horsham',
  'mid-sussex',
  'worthing',
  'bromsgrove',
  'malvern-hills',
  'redditch',
  'worcester',
  'wychavon',
  'wyre-forest',
  'st-albans',
  'welwyn-hatfield',
  'east-hertfordshire',
  'stevenage',
  'east-suffolk',
  'west-suffolk',
  'somerset-west-and-taunton',
  'bolton',
  'bury',
  'manchester',
  'oldham',
  'rochdale',
  'salford',
  'stockport',
  'tameside',
  'trafford',
  'wigan',
  'knowsley',
  'liverpool',
  'st-helens',
  'sefton',
  'wirral',
  'barnsley',
  'doncaster',
  'rotherham',
  'sheffield',
  'newcastle-upon-tyne',
  'north-tyneside',
  'south-tyneside',
  'sunderland',
  'birmingham',
  'coventry',
  'dudley',
  'sandwell',
  'solihull',
  'walsall',
  'wolverhampton',
  'bradford',
  'calderdale',
  'kirklees',
  'leeds',
  'wakefield',
  'gateshead',
  'city-of-london',
  'barking-and-dagenham',
  'barnet',
  'bexley',
  'brent',
  'bromley',
  'camden',
  'croydon',
  'ealing',
  'enfield',
  'greenwich',
  'hackney',
  'hammersmith-and-fulham',
  'haringey',
  'harrow',
  'havering',
  'hillingdon',
  'hounslow',
  'islington',
  'kensington-and-chelsea',
  'kingston-upon-thames',
  'lambeth',
  'lewisham',
  'merton',
  'newham',
  'redbridge',
  'richmond-upon-thames',
  'southwark',
  'sutton',
  'tower-hamlets',
  'waltham-forest',
  'wandsworth',
  'westminster',
  'buckinghamshire',
  'north-northamptonshire',
  'west-northamptonshire',
  'bournemouth',
  'poole',
  'christchurch',
  'east-dorset',
  'north-dorset',
  'purbeck',
  'west-dorset',
  'weymouth-and-portland',
  'taunton-deane',
  'west-somerset',
  'forest-heath',
  'st-edmundsbury',
  'suffolk-coastal',
  'waveney',
  'cumberland',
  'westmorland-and-furness',
  'north-yorkshire',
  'somerset',
] as const;

export type LocalAuthorityId = (typeof LOCAL_AUTHORITY_IDS)[number];
export type PrivateCompanyId = (typeof PRIVATE_COMPANY_IDS)[number];
export type TransportAuthorityId = (typeof TRANSPORT_AUTHORITY_IDS)[number];

export const PRIVATE_COMPANIES = [
  { id: 'horizon' as const, name: 'Horizon Parking' },
  { id: 'parkingEye' as const, name: 'ParkingEye' },
  { id: 'euro-car-parks' as const, name: 'Euro Car Parks' },
  { id: 'smart-parking' as const, name: 'Smart Parking' },
  { id: 'apcoa-parking' as const, name: 'APCOA Parking' },
  { id: 'ncp' as const, name: 'NCP' },
  { id: 'q-park' as const, name: 'Q-Park' },
  { id: 'indigo-park' as const, name: 'Indigo Park' },
  { id: 'excel-parking-services' as const, name: 'Excel Parking Services' },
  { id: 'parking-control-management' as const, name: 'Parking Control Management' },
  { id: 'vehicle-control-services' as const, name: 'Vehicle Control Services' },
  { id: 'uk-parking-control' as const, name: 'UK Parking Control' },
  { id: 'civil-enforcement-ltd' as const, name: 'Civil Enforcement Ltd' },
  { id: 'cp-plus' as const, name: 'CP Plus' },
  { id: 'saba-parking' as const, name: 'Saba Parking' },
  { id: 'town-centre-parking' as const, name: 'Town Centre Parking' },
  { id: 'britannia-parking' as const, name: 'Britannia Parking' },
  { id: 'gemini-parking-solutions' as const, name: 'Gemini Parking Solutions' },
  { id: 'athena-anpr' as const, name: 'Athena ANPR' },
  { id: 'alliance-parking-management' as const, name: 'Alliance Parking Management' },
  { id: 'premier-park' as const, name: 'Premier Park' },
  { id: 'one-parking' as const, name: 'One Parking' },
  { id: 'g24' as const, name: 'G24' },
  { id: 'ctl-parking' as const, name: 'CTL Parking' },
  { id: 'highview-parking' as const, name: 'Highview Parking' },
  { id: 'nationwide-parking-enforcement' as const, name: 'Nationwide Parking Enforcement' },
  { id: 'met-parking-services' as const, name: 'Met Parking Services' },
  { id: 'new-generation-parking' as const, name: 'New Generation Parking' },
  { id: 'park-watch' as const, name: 'Park Watch' },
  { id: 'armtrac' as const, name: 'Armtrac' },
  { id: 'swift-parking-services' as const, name: 'Swift Parking Services' },
  { id: 'eagle-parking' as const, name: 'Eagle Parking' },
  { id: 'resolute-parking' as const, name: 'Resolute Parking' },
  { id: 'citrus-parking' as const, name: 'Citrus Parking' },
  { id: 'northern-parking-services' as const, name: 'Northern Parking Services' },
  { id: 'flash-park' as const, name: 'Flash Park' },
  { id: 'parkmaven' as const, name: 'ParkMaven' },
  { id: 'cambridgeshire-parking-enforcement' as const, name: 'Cambridgeshire Parking Enforcement' },
  { id: 'council-responsible-parking' as const, name: 'Council Responsible Parking' },
  { id: 'patrol-parking' as const, name: 'Patrol Parking' },
  { id: 'all-parking-services' as const, name: 'All Parking Services' },
  { id: 'apg-parking' as const, name: 'APG Parking' },
  { id: 'creative-car-park' as const, name: 'Creative Car Park' },
  { id: 'ace-parking' as const, name: 'Ace Parking' },
  { id: 'zenith-parking' as const, name: 'Zenith Parking' },
  { id: 'link-parking' as const, name: 'Link Parking' },
  { id: 'moto-parking' as const, name: 'Moto Parking' },
  { id: 'orbit-parking' as const, name: 'Orbit Parking' },
  { id: 'minster-baywatch' as const, name: 'Minster Baywatch' },
  { id: 'north-west-parking-enforcement' as const, name: 'North West Parking Enforcement' },
] as const;

export const TRANSPORT_AUTHORITIES = [
  { id: 'tfl' as const, name: 'Transport for London' },
] as const;

/** Convert a slug like "kensington-and-chelsea" to "Kensington and Chelsea" */
export const slugToDisplayName = (slug: string): string => {
  return slug
    .split('-')
    .map((word) => {
      if (word === 'and') return 'and';
      if (word === 'of') return 'of';
      if (word === 'upon') return 'upon';
      if (word === 'in') return 'in';
      if (word === 'the') return 'the';
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
};

/** Reverse lookup: find the slug for a given display name */
export const displayNameToSlug = (name: string): string | undefined => {
  const lower = name.toLowerCase();

  // Check private companies by their explicit name field (handles cases like "NCP", "APCOA Parking")
  const privateMatch = PRIVATE_COMPANIES.find(
    (c) => c.name.toLowerCase() === lower,
  );
  if (privateMatch) return privateMatch.id;

  // Check transport authorities by name
  const transportMatch = TRANSPORT_AUTHORITIES.find(
    (t) => t.name.toLowerCase() === lower,
  );
  if (transportMatch) return transportMatch.id;

  // Check local authorities by slug → display name conversion (exact match)
  const exactMatch = LOCAL_AUTHORITY_IDS.find(
    (slug) => slugToDisplayName(slug).toLowerCase() === lower,
  );
  if (exactMatch) return exactMatch;

  // Check ISSUER_ADDRESSES formalName (handles "London Borough of Lewisham", "City of York Council", etc.)
  const addressKeys = Object.keys(ISSUER_ADDRESSES);
  const formalMatch = addressKeys.find(
    (key) => ISSUER_ADDRESSES[key]?.formalName.toLowerCase() === lower,
  );
  if (formalMatch) return formalMatch;

  // Partial match for private companies — OCR may extract "Euro Car Parks (UK) Ltd" but list has "Euro Car Parks"
  const privatePartialMatch = PRIVATE_COMPANIES.find(
    (c) => lower.includes(c.name.toLowerCase()) || c.name.toLowerCase().includes(lower),
  );
  if (privatePartialMatch) return privatePartialMatch.id;

  // Partial match for transport authorities
  const transportPartialMatch = TRANSPORT_AUTHORITIES.find(
    (t) => lower.includes(t.name.toLowerCase()) || t.name.toLowerCase().includes(lower),
  );
  if (transportPartialMatch) return transportPartialMatch.id;

  // Strip common suffixes/prefixes and retry: "Lewisham Council" → "Lewisham", "Borough of X" → "X"
  const stripped = lower
    .replace(/\b(borough|city|county|district|metropolitan|unitary)\s+(council|authority)\b/g, '')
    .replace(/\b(london borough of|royal borough of|city of|council of the)\b/g, '')
    .replace(/\bcouncil\b/g, '')
    .replace(/\bparking\s*services?\b/g, '')
    .trim();

  if (stripped && stripped !== lower) {
    const strippedMatch = LOCAL_AUTHORITY_IDS.find(
      (slug) => slugToDisplayName(slug).toLowerCase() === stripped,
    );
    if (strippedMatch) return strippedMatch;
  }

  return undefined;
};

export const getIssuerType = (issuerName: string): 'COUNCIL' | 'TFL' | 'PRIVATE_COMPANY' => {
  const slug = displayNameToSlug(issuerName);
  if (!slug) return 'COUNCIL'; // fallback for unknown/custom issuers
  if ((TRANSPORT_AUTHORITY_IDS as readonly string[]).includes(slug)) return 'TFL';
  if ((PRIVATE_COMPANY_IDS as readonly string[]).includes(slug)) return 'PRIVATE_COMPANY';
  return 'COUNCIL';
};

export type IssuerAddress = {
  formalName: string;
  department?: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  postcode: string;
};

export const ISSUER_ADDRESSES: Partial<Record<string, IssuerAddress>> = {
  'adur': {
    formalName: 'Adur & Worthing Councils',
    department: 'Parking Services',
    addressLine1: 'Worthing Town Hall',
    addressLine2: 'Chapel Road',
    city: 'Worthing',
    postcode: 'BN11 1HA',
  },
  'allerdale': {
    formalName: 'Allerdale Borough Council',
    department: 'Parking Services',
    addressLine1: 'Allerdale House',
    city: 'Workington',
    postcode: 'CA14 3YJ',
  },
  'amber-valley': {
    formalName: 'Amber Valley Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Market Place',
    city: 'Ripley',
    postcode: 'DE5 3BT',
  },
  'arun': {
    formalName: 'Arun District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Maltravers Road',
    city: 'Littlehampton',
    postcode: 'BN17 5LF',
  },
  'ashfield': {
    formalName: 'Ashfield District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, Urban Road',
    city: 'Kirkby-in-Ashfield',
    postcode: 'NG17 8DA',
  },
  'ashford': {
    formalName: 'Ashford Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Tannery Lane',
    city: 'Ashford',
    postcode: 'TN23 1PL',
  },
  'aylesbury-vale': {
    formalName: 'Buckinghamshire Council',
    department: 'Parking Services',
    addressLine1: 'Walton Street Offices',
    city: 'Aylesbury',
    postcode: 'HP20 1UA',
  },
  'babergh': {
    formalName: 'Babergh District Council',
    department: 'Parking Services',
    addressLine1: 'Endeavour House',
    addressLine2: '8 Russell Road',
    city: 'Ipswich',
    postcode: 'IP1 2BX',
  },
  'barking-and-dagenham': {
    formalName: 'London Borough of Barking and Dagenham',
    department: 'Parking Services',
    addressLine1: 'Barking Town Hall, 1 Town Square',
    city: 'Barking',
    postcode: 'IG11 7LU',
  },
  'barnet': {
    formalName: 'London Borough of Barnet',
    department: 'Parking Services',
    addressLine1: 'PO Box 70469',
    city: 'London',
    postcode: 'SE26 9GQ',
  },
  'barnsley': {
    formalName: 'Barnsley Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 634',
    city: 'Barnsley',
    postcode: 'S70 9GG',
  },
  'barrow-in-furness': {
    formalName: 'Westmorland and Furness Council',
    department: 'Parking Services',
    addressLine1: 'South Lakeland House, Lowther Street',
    city: 'Kendal',
    postcode: 'LA9 4DQ',
  },
  'basildon': {
    formalName: 'South Essex Parking Partnership',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Duke Street',
    city: 'Chelmsford',
    postcode: 'CM1 1JE',
  },
  'basingstoke-and-deane': {
    formalName: 'Basingstoke and Deane Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices',
    addressLine2: 'London Road',
    city: 'Basingstoke',
    postcode: 'RG21 4AH',
  },
  'bassetlaw': {
    formalName: 'Bassetlaw District Council',
    department: 'Parking Services',
    addressLine1: 'Queen\'s Buildings, Potter Street',
    city: 'Worksop',
    postcode: 'S80 2AH',
  },
  'bath-and-north-east-somerset': {
    formalName: 'Bath and North East Somerset Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 5197',
    city: 'Bath',
    postcode: 'BA1 0UF',
  },
  'bedford': {
    formalName: 'Bedford Borough Council',
    department: 'Parking Services',
    addressLine1: '26 Harpur Street',
    city: 'Bedford',
    postcode: 'MK40 1LG',
  },
  'bexley': {
    formalName: 'London Borough of Bexley',
    department: 'Bexley Parking Services',
    addressLine1: 'PO Box 1166',
    addressLine2: 'Wellington House',
    city: 'Uxbridge',
    postcode: 'UB8 9BD',
  },
  'birmingham': {
    formalName: 'Birmingham City Council',
    department: 'Parking Services',
    addressLine1: 'Council House',
    addressLine2: 'Victoria Square',
    city: 'Birmingham',
    postcode: 'B1 1BB',
  },
  'blaby': {
    formalName: 'Leicestershire County Council',
    department: 'Notice Processing Centre',
    addressLine1: 'PO Box 9983',
    city: 'Leicester',
    postcode: 'LE3 7DD',
  },
  'blackburn-with-darwen': {
    formalName: 'Blackburn with Darwen Borough Council',
    department: 'Parking Services',
    addressLine1: 'Darwen Town Hall',
    addressLine2: 'Croft Street',
    city: 'Darwen',
    postcode: 'BB3 1BQ',
  },
  'blackpool': {
    formalName: 'Blackpool Council',
    department: 'Parking Services',
    addressLine1: '1 Bickerstaffe Sq., Talbot Rd.',
    city: 'Blackpool',
    postcode: 'FY1 3AH',
  },
  'bolsover': {
    formalName: 'Bolsover District Council',
    department: 'Parking Services',
    addressLine1: 'The Arc',
    addressLine2: 'High Street',
    city: 'Clowne',
    postcode: 'S43 4JY',
  },
  'bolton': {
    formalName: 'Bolton Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 434',
    city: 'Bolton',
    postcode: 'BL1 4FD',
  },
  'boston': {
    formalName: 'Boston Borough Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Buildings',
    addressLine2: 'West Street',
    city: 'Boston',
    postcode: 'PE21 8QR',
  },
  'bournemouth': {
    formalName: 'BCP Council',
    department: 'Parking Administration',
    addressLine1: 'Civic Centre, Bourne Avenue',
    city: 'Bournemouth',
    postcode: 'BH2 6DY',
  },
  'bournemouth-christchurch-and-poole': {
    formalName: 'Bournemouth, Christchurch and Poole Council',
    department: 'Parking Administration',
    addressLine1: 'BCP Council Civic Centre, Bourne Avenue',
    city: 'Bournemouth',
    postcode: 'BH2 6DY',
  },
  'bracknell-forest': {
    formalName: 'Bracknell Forest Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 320',
    city: 'Sheffield',
    postcode: 'S98 1AP',
  },
  'bradford': {
    formalName: 'City of Bradford Metropolitan District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 848',
    city: 'Bradford',
    postcode: 'BD1 5UH',
  },
  'braintree': {
    formalName: 'Braintree District Council',
    department: 'Parking Services',
    addressLine1: 'Causeway House, Bocking End',
    city: 'Braintree',
    postcode: 'CM7 9HB',
  },
  'breckland': {
    formalName: 'Breckland District Council',
    department: 'Parking Services',
    addressLine1: 'Elizabeth House',
    addressLine2: 'Walpole Loke',
    city: 'Dereham',
    postcode: 'NR19 1EE',
  },
  'brent': {
    formalName: 'London Borough of Brent',
    department: 'Parking Services',
    addressLine1: 'PO Box 210',
    city: 'Sheffield',
    postcode: 'S98 1NE',
  },
  'brentwood': {
    formalName: 'Brentwood Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Ingrave Road',
    city: 'Brentwood',
    postcode: 'CM15 8AY',
  },
  'brighton-and-hove': {
    formalName: 'Brighton & Hove City Council',
    department: 'Parking Services',
    addressLine1: 'Hove Town Hall, Norton Road',
    city: 'Hove',
    postcode: 'BN3 3BQ',
  },
  'bristol-city-of': {
    formalName: 'Bristol City Council',
    department: 'Parking Services',
    addressLine1: 'B Bond Warehouse (5th Floor)',
    addressLine2: 'Smeaton Road',
    city: 'Bristol',
    postcode: 'BS1 6XN',
  },
  'broadland': {
    formalName: 'South Norfolk and Broadland District Council',
    department: 'Parking Services',
    addressLine1: 'The Horizon Centre, Peachman Way, Broadland Business Park',
    city: 'Norwich',
    postcode: 'NR7 0WF',
  },
  'bromley': {
    formalName: 'London Borough of Bromley',
    department: 'Parking Services',
    addressLine1: 'PO Box 1166, Wellington House',
    city: 'Uxbridge',
    postcode: 'UB8 9BD',
  },
  'bromsgrove': {
    formalName: 'Bromsgrove District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Queen Elizabeth Drive',
    city: 'Pershore',
    postcode: 'WR10 1PT',
  },
  'broxbourne': {
    formalName: 'Borough of Broxbourne Council',
    department: 'Parking Services',
    addressLine1: 'Bishops\' College, Churchgate',
    city: 'Cheshunt',
    postcode: 'EN8 9XQ',
  },
  'broxtowe': {
    formalName: 'Broxtowe Borough Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices',
    addressLine2: 'Foster Avenue',
    city: 'Beeston',
    postcode: 'NG9 1AB',
  },
  'buckinghamshire': {
    formalName: 'Buckinghamshire Council',
    department: 'Parking Services Team',
    addressLine1: 'Walton Street Office, Walton Street',
    city: 'Aylesbury',
    postcode: 'HP20 1UA',
  },
  'burnley': {
    formalName: 'Burnley Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Manchester Road',
    city: 'Burnley',
    postcode: 'BB11 9SA',
  },
  'bury': {
    formalName: 'Bury Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Knowsley Street',
    city: 'Bury',
    postcode: 'BL9 0SW',
  },
  'calderdale': {
    formalName: 'Calderdale Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Crossley Street',
    city: 'Halifax',
    postcode: 'HX1 1UJ',
  },
  'cambridge': {
    formalName: 'Cambridge City Council',
    department: 'Parking Services',
    addressLine1: 'Mandela House, 4 Regent Street',
    city: 'Cambridge',
    postcode: 'CB2 1BY',
  },
  'camden': {
    formalName: 'London Borough of Camden',
    department: 'Parking Services',
    addressLine1: '5 Pancras Square',
    city: 'London',
    postcode: 'N1C 4AG',
  },
  'cannock-chase': {
    formalName: 'Cannock Chase District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 4907',
    city: 'Cannock',
    postcode: 'WS11 9AQ',
  },
  'canterbury': {
    formalName: 'Canterbury City Council',
    department: 'Parking Services',
    addressLine1: 'The Beaney House of Art and Knowledge',
    addressLine2: '18 High Street',
    city: 'Canterbury',
    postcode: 'CT1 2RA',
  },
  'carlisle': {
    formalName: 'Cumberland Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Rickergate',
    city: 'Carlisle',
    postcode: 'CA3 8QG',
  },
  'castle-point': {
    formalName: 'South Essex Parking Partnership',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Duke Street',
    city: 'Chelmsford',
    postcode: 'CM1 1JE',
  },
  'central-bedfordshire': {
    formalName: 'Central Bedfordshire Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 352',
    city: 'Sheffield',
    postcode: 'S98 1YE',
  },
  'charnwood': {
    formalName: 'Charnwood Borough Council',
    department: 'Parking Services',
    addressLine1: 'Southfield Road',
    city: 'Loughborough',
    postcode: 'LE11 2TN',
  },
  'chelmsford': {
    formalName: 'Chelmsford City Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Duke Street',
    city: 'Chelmsford',
    postcode: 'CM1 1JE',
  },
  'cheltenham': {
    formalName: 'Cheltenham Borough Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Offices',
    addressLine2: 'Promenade',
    city: 'Cheltenham',
    postcode: 'GL50 9SA',
  },
  'cherwell': {
    formalName: 'Cherwell District Council',
    department: 'Parking Services',
    addressLine1: '39 Castle Quay',
    city: 'Banbury',
    postcode: 'OX16 5FD',
  },
  'cheshire-east': {
    formalName: 'Cheshire East Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Buildings',
    addressLine2: 'Earle Street',
    city: 'Crewe',
    postcode: 'CW1 2BJ',
  },
  'cheshire-west-and-chester': {
    formalName: 'Cheshire West and Chester Council',
    department: 'Parking Services',
    addressLine1: 'The Portal, Wellington Road',
    city: 'Ellesmere Port',
    postcode: 'CH65 0BA',
  },
  'chesterfield': {
    formalName: 'Chesterfield Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Rose Hill',
    city: 'Chesterfield',
    postcode: 'S40 1LP',
  },
  'chichester': {
    formalName: 'Chichester District Council',
    department: 'Parking Services',
    addressLine1: 'East Pallant House',
    city: 'Chichester',
    postcode: 'PO19 1TY',
  },
  'chiltern': {
    formalName: 'Buckinghamshire Council',
    department: 'Parking Services',
    addressLine1: 'Chiltern Avenue',
    city: 'Amersham',
    postcode: 'HP6 5AH',
  },
  'chorley': {
    formalName: 'Chorley Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices',
    addressLine2: 'Union Street',
    city: 'Chorley',
    postcode: 'PR7 2AL',
  },
  'christchurch': {
    formalName: 'BCP Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 843',
    city: 'Bournemouth',
    postcode: 'BH1 9QY',
  },
  'city-of-london': {
    formalName: 'City of London Corporation',
    department: 'Parking',
    addressLine1: 'Guildhall, PO Box 270',
    city: 'London',
    postcode: 'EC2P 2EJ',
  },
  'colchester': {
    formalName: 'North Essex Parking Partnership',
    department: 'Parking Services',
    addressLine1: 'PO Box 5575',
    addressLine2: 'Town Hall',
    city: 'Colchester',
    postcode: 'CO1 9LT',
  },
  'copeland': {
    formalName: 'Copeland Borough Council',
    department: 'Parking Services',
    addressLine1: 'Whitehaven Commercial Park',
    addressLine2: 'Moresby Parks',
    city: 'Whitehaven',
    postcode: 'CA28 8YD',
  },
  'corby': {
    formalName: 'North Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'Sheerness House, 41 Meadow Road',
    city: 'Kettering',
    postcode: 'NN16 8TL',
  },
  'cornwall': {
    formalName: 'Cornwall Council',
    department: 'Parking team',
    addressLine1: 'PO Box 664',
    city: 'Truro',
    postcode: 'TR1 9DH',
  },
  'cotswold': {
    formalName: 'Cotswold District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 335',
    city: 'Cirencester',
    postcode: 'GL7 9JH',
  },
  'county-durham': {
    formalName: 'Durham County Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 115',
    city: 'Spennymoor',
    postcode: 'DL16 9BX',
  },
  'coventry': {
    formalName: 'Coventry City Council',
    department: 'Parking Services (Appeals and Permits)',
    addressLine1: 'PO Box 7097',
    city: 'Coventry',
    postcode: 'CV6 9SL',
  },
  'craven': {
    formalName: 'North Yorkshire Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, Racecourse Lane',
    city: 'Northallerton',
    postcode: 'DL7 8AD',
  },
  'crawley': {
    formalName: 'Crawley Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    addressLine2: 'The Boulevard',
    city: 'Crawley',
    postcode: 'RH10 1UZ',
  },
  'croydon': {
    formalName: 'Croydon Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 1462',
    city: 'Croydon',
    postcode: 'CR9 1WX',
  },
  'cumberland': {
    formalName: 'Cumberland Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 96',
    city: 'Workington',
    postcode: 'CA14 9BR',
  },
  'dacorum': {
    formalName: 'Dacorum Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 921',
    city: 'Hemel Hempstead',
    postcode: 'HP1 1ZP',
  },
  'darlington': {
    formalName: 'Darlington Borough Council',
    department: 'Xentrall Shared Services, Transactional Finance',
    addressLine1: 'PO Box 877',
    city: 'Stockton-on-Tees',
    postcode: 'TS19 1JA',
  },
  'dartford': {
    formalName: 'Dartford Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Home Gardens',
    city: 'Dartford',
    postcode: 'DA1 1DR',
  },
  'daventry': {
    formalName: 'West Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'Icon Innovation Centre',
    addressLine2: 'Eastern Way',
    city: 'Daventry',
    postcode: 'NN11 0QB',
  },
  'derby': {
    formalName: 'Derby City Council',
    department: 'Parking Services',
    addressLine1: 'Council House, Corporation Street',
    city: 'Derby',
    postcode: 'DE1 2FS',
  },
  'derbyshire-dales': {
    formalName: 'Derbyshire Dales District Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Bank Road',
    city: 'Matlock',
    postcode: 'DE4 3NN',
  },
  'doncaster': {
    formalName: 'City of Doncaster Council',
    department: 'Parking Services',
    addressLine1: 'Civic Office, Waterdale',
    city: 'Doncaster',
    postcode: 'DN1 3BU',
  },
  'dorset': {
    formalName: 'Dorset Council',
    department: 'Parking Services',
    addressLine1: 'Charminster Depot, Wanchard Lane',
    city: 'Dorchester',
    postcode: 'DT2 9RP',
  },
  'dover': {
    formalName: 'Dover District Council',
    department: 'Parking Services',
    addressLine1: 'White Cliffs Business Park, Dover',
    city: 'Dover',
    postcode: 'CT16 3PJ',
  },
  'dudley': {
    formalName: 'Dudley Metropolitan Borough Council',
    department: 'Parking Management',
    addressLine1: 'Lister Road Depot',
    city: 'Dudley',
    postcode: 'DY2 8JW',
  },
  'ealing': {
    formalName: 'Ealing Council',
    department: 'Parking services',
    addressLine1: 'PO Box 46264',
    city: 'Ealing',
    postcode: 'W5 2UN',
  },
  'east-cambridgeshire': {
    formalName: 'East Cambridgeshire District Council',
    department: 'Parking Services',
    addressLine1: 'The Grange, Nutholt Lane',
    city: 'Ely',
    postcode: 'CB7 4EE',
  },
  'east-devon': {
    formalName: 'East Devon District Council',
    department: 'Parking Services',
    addressLine1: 'Blackdown House, Border Road, Heathpark Industrial Estate',
    city: 'Honiton',
    postcode: 'EX14 1EJ',
  },
  'east-dorset': {
    formalName: 'Dorset Council',
    department: 'Parking Services',
    addressLine1: 'Charminster Depot, Wanchard Lane',
    addressLine2: 'Charminster',
    city: 'Dorchester',
    postcode: 'DT2 9RP',
  },
  'east-hampshire': {
    formalName: 'East Hampshire District Council',
    department: 'Parking and Traffic Management',
    addressLine1: 'PO Box 263',
    city: 'Petersfield',
    postcode: 'GU32 9FD',
  },
  'east-hertfordshire': {
    formalName: 'East Hertfordshire District Council',
    department: 'Highways and Parking',
    addressLine1: 'PO Box 153',
    addressLine2: 'Gunnels Wood Road',
    city: 'Stevenage',
    postcode: 'SG1 2ST',
  },
  'east-lindsey': {
    formalName: 'East Lindsey District Council',
    department: 'Parking Services',
    addressLine1: 'Tedder Hall, Manby Park',
    city: 'Louth',
    postcode: 'LN11 8UP',
  },
  'east-northamptonshire': {
    formalName: 'North Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Offices',
    addressLine2: 'Bowling Green Road',
    city: 'Kettering',
    postcode: 'NN15 7QX',
  },
  'east-riding-of-yorkshire': {
    formalName: 'East Riding of Yorkshire Council',
    department: 'CPE',
    addressLine1: 'PO Box 294',
    city: 'Beverley',
    postcode: 'HU17 6FB',
  },
  'east-staffordshire': {
    formalName: 'East Staffordshire Borough Council',
    department: 'Parking Services',
    addressLine1: 'The Town Hall, King Edward Place',
    city: 'Burton upon Trent',
    postcode: 'DE14 2EB',
  },
  'east-suffolk': {
    formalName: 'East Suffolk Council',
    department: 'Parking Services',
    addressLine1: 'Riverside',
    addressLine2: '4 Canning Road',
    city: 'Lowestoft',
    postcode: 'NR33 0EQ',
  },
  'eastbourne': {
    formalName: 'Eastbourne Borough Council',
    department: 'Parking Services',
    addressLine1: '1 Grove Road',
    city: 'Eastbourne',
    postcode: 'BN21 4TW',
  },
  'eastleigh': {
    formalName: 'Eastleigh Borough Council',
    department: 'Parking Services',
    addressLine1: 'Eastleigh House, Upper Market Street',
    city: 'Eastleigh',
    postcode: 'SO50 9YN',
  },
  'eden': {
    formalName: 'Westmorland and Furness Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    city: 'Kendal',
    postcode: 'LA9 4DL',
  },
  'elmbridge': {
    formalName: 'Elmbridge Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, High Street',
    city: 'Esher',
    postcode: 'KT10 9SD',
  },
  'enfield': {
    formalName: 'London Borough of Enfield',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Silver Street',
    city: 'Enfield',
    postcode: 'EN1 3XD',
  },
  'epping-forest': {
    formalName: 'Epping Forest District Council',
    department: 'Parking Services',
    addressLine1: '323 High Street',
    city: 'Epping',
    postcode: 'CM16 4BZ',
  },
  'epsom-and-ewell': {
    formalName: 'Epsom and Ewell Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, The Parade',
    city: 'Epsom',
    postcode: 'KT18 5BY',
  },
  'erewash': {
    formalName: 'Erewash Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Derby Road',
    city: 'Long Eaton',
    postcode: 'NG10 1HU',
  },
  'exeter': {
    formalName: 'Exeter City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 811',
    city: 'Exeter',
    postcode: 'EX1 9WA',
  },
  'fareham': {
    formalName: 'Fareham Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices, Civic Way',
    city: 'Fareham',
    postcode: 'PO16 7AZ',
  },
  'fenland': {
    formalName: 'Fenland District Council',
    department: 'Parking Services',
    addressLine1: 'Fenland Hall, County Road',
    city: 'March',
    postcode: 'PE15 8NQ',
  },
  'folkestone-and-hythe': {
    formalName: 'Folkestone & Hythe District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Castle Hill Avenue',
    city: 'Folkestone',
    postcode: 'CT20 2QY',
  },
  'forest-heath': {
    formalName: 'West Suffolk Council',
    department: 'Parking Services',
    addressLine1: 'West Suffolk House, Western Way',
    city: 'Bury St Edmunds',
    postcode: 'IP33 3YU',
  },
  'forest-of-dean': {
    formalName: 'Forest of Dean District Council',
    department: 'Parking Services',
    addressLine1: 'High Street',
    city: 'Coleford',
    postcode: 'GL16 8HG',
  },
  'fylde': {
    formalName: 'Fylde Borough Council',
    department: 'Parking Services',
    addressLine1: 'The Town Hall',
    addressLine2: 'St Annes Road West',
    city: 'Lytham St Annes',
    postcode: 'FY8 1LW',
  },
  'gateshead': {
    formalName: 'Gateshead Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Regent Street',
    city: 'Gateshead',
    postcode: 'NE8 1HH',
  },
  'gedling': {
    formalName: 'Gedling Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Arnot Hill House, Arnold',
    city: 'Nottingham',
    postcode: 'NG5 6LU',
  },
  'gloucester': {
    formalName: 'Gloucester City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 3584',
    city: 'Chippenham',
    postcode: 'SN15 9EF',
  },
  'gosport': {
    formalName: 'Gosport Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, High Street',
    city: 'Gosport',
    postcode: 'PO12 1EB',
  },
  'gravesham': {
    formalName: 'Gravesham Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Windmill Street',
    city: 'Gravesend',
    postcode: 'DA12 1AU',
  },
  'great-yarmouth': {
    formalName: 'Great Yarmouth Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Hall Plain',
    city: 'Great Yarmouth',
    postcode: 'NR30 2QF',
  },
  'greenwich': {
    formalName: 'Royal Borough of Greenwich',
    department: 'Parking Services',
    addressLine1: 'The Woolwich Centre',
    addressLine2: '35 Wellington Street',
    city: 'London',
    postcode: 'SE18 6HQ',
  },
  'guildford': {
    formalName: 'Guildford Borough Council',
    department: 'Parking Services',
    addressLine1: 'Millmead House',
    addressLine2: 'Millmead',
    city: 'Guildford',
    postcode: 'GU2 4BB',
  },
  'hackney': {
    formalName: 'London Borough of Hackney',
    department: 'Parking Services',
    addressLine1: 'PO Box 39054',
    city: 'London',
    postcode: 'E8 1WS',
  },
  'halton': {
    formalName: 'Halton Borough Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Building',
    addressLine2: 'Kingsway',
    city: 'Widnes',
    postcode: 'WA8 7QF',
  },
  'hambleton': {
    formalName: 'Hambleton District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Stone Cross',
    city: 'Northallerton',
    postcode: 'DL6 2UU',
  },
  'hammersmith-and-fulham': {
    formalName: 'London Borough of Hammersmith and Fulham',
    department: 'Parking Services',
    addressLine1: 'Town Hall, King Street',
    city: 'London',
    postcode: 'W6 9JU',
  },
  'harborough': {
    formalName: 'Harborough District Council',
    department: 'Parking Services',
    addressLine1: 'The Symington Building',
    addressLine2: 'Adam and Eve Street',
    city: 'Market Harborough',
    postcode: 'LE16 7AG',
  },
  'haringey': {
    formalName: 'London Borough of Haringey',
    department: 'Haringey Parking Services',
    addressLine1: 'PO Box 321',
    city: 'Sheffield',
    postcode: 'S98 1AS',
  },
  'harlow': {
    formalName: 'Harlow District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, The Water Gardens',
    city: 'Harlow',
    postcode: 'CM20 1WG',
  },
  'harrogate': {
    formalName: 'North Yorkshire Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, Racecourse Lane',
    city: 'Northallerton',
    postcode: 'DL7 8AD',
  },
  'harrow': {
    formalName: 'London Borough of Harrow',
    department: 'Parking Enforcement',
    addressLine1: 'PO Box 951',
    city: 'Harrow',
    postcode: 'HA3 3RJ',
  },
  'hart': {
    formalName: 'Hart District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices',
    addressLine2: 'Harlands Road',
    city: 'Fleet',
    postcode: 'GU51 4AE',
  },
  'hartlepool': {
    formalName: 'Hartlepool Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Victoria Road',
    city: 'Hartlepool',
    postcode: 'TS24 8AY',
  },
  'hastings': {
    formalName: 'Hastings Borough Council',
    department: 'Parking Services',
    addressLine1: 'Muriel Matters House, Breeds Place',
    city: 'Hastings',
    postcode: 'TN34 3UY',
  },
  'havant': {
    formalName: 'Havant Borough Council',
    department: 'Parking Services',
    addressLine1: 'Public Service Plaza, Civic Centre Road',
    city: 'Havant',
    postcode: 'PO9 2AX',
  },
  'havering': {
    formalName: 'London Borough of Havering',
    department: 'Traffic & Parking Control',
    addressLine1: 'Town Hall',
    city: 'Romford',
    postcode: 'RM1 3BB',
  },
  'herefordshire-county-of': {
    formalName: 'Herefordshire Council',
    department: 'Parking Services',
    addressLine1: 'Plough Lane',
    city: 'Hereford',
    postcode: 'HR4 0LE',
  },
  'hertsmere': {
    formalName: 'Hertsmere Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices, Elstree Way',
    city: 'Borehamwood',
    postcode: 'WD6 1WA',
  },
  'high-peak': {
    formalName: 'High Peak Borough Council',
    department: 'Parking Services',
    addressLine1: 'Buxton Town Hall, Market Place',
    city: 'Buxton',
    postcode: 'SK17 6EL',
  },
  'hillingdon': {
    formalName: 'Hillingdon Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, High Street',
    city: 'Uxbridge',
    postcode: 'UB8 1UW',
  },
  'hinckley-and-bosworth': {
    formalName: 'Hinckley & Bosworth Borough Council',
    department: 'Parking Services',
    addressLine1: 'Hinckley Hub, Rugby Road',
    city: 'Hinckley',
    postcode: 'LE10 0FR',
  },
  'horizon': {
    formalName: 'Horizon Parking Ltd',
    department: 'Penalty Charge Notice Department',
    addressLine1: 'Finitor House',
    addressLine2: '2 Hanbury Road',
    city: 'Chelmsford',
    postcode: 'CM1 3AE',
  },
  'horsham': {
    formalName: 'Horsham District Council',
    department: 'Parking Services',
    addressLine1: 'Albery House',
    addressLine2: 'Springfield Road',
    city: 'Horsham',
    postcode: 'RH12 2GB',
  },
  'hounslow': {
    formalName: 'London Borough of Hounslow',
    department: 'Parking Services',
    addressLine1: 'Hounslow House',
    addressLine2: '7 Bath Road',
    city: 'Hounslow',
    postcode: 'TW3 3EB',
  },
  'huntingdonshire': {
    formalName: 'Huntingdonshire District Council',
    department: 'Parking Services',
    addressLine1: 'Pathfinder House, St Mary\'s Street',
    city: 'Huntingdon',
    postcode: 'PE29 3TN',
  },
  'hyndburn': {
    formalName: 'Hyndburn Borough Council',
    department: 'Parking Services',
    addressLine1: 'Scaitcliffe House',
    addressLine2: 'Ormerod Street',
    city: 'Accrington',
    postcode: 'BB5 0PF',
  },
  'ipswich': {
    formalName: 'Ipswich Borough Council',
    department: 'Parking Services',
    addressLine1: 'Grafton House',
    city: 'Ipswich',
    postcode: 'IP1 2SJ',
  },
  'isle-of-wight': {
    formalName: 'Isle of Wight Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, High Street',
    city: 'Newport',
    postcode: 'PO30 1UD',
  },
  'isles-of-scilly': {
    formalName: 'Council of the Isles of Scilly',
    department: 'Parking Services',
    addressLine1: 'Town Hall, St Marys',
    city: 'Isles of Scilly',
    postcode: 'TR21 0LW',
  },
  'islington': {
    formalName: 'London Borough of Islington',
    department: 'Islington Parking Services',
    addressLine1: 'PO Box 2019',
    city: 'Pershore',
    postcode: 'WR10 9BN',
  },
  'kensington-and-chelsea': {
    formalName: 'Royal Borough of Kensington and Chelsea',
    department: 'Parking Services',
    addressLine1: 'Customer Service Centre, Town Hall, Hornton Street',
    city: 'London',
    postcode: 'W8 7NX',
  },
  'kettering': {
    formalName: 'North Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Offices, Bowling Green Road',
    city: 'Kettering',
    postcode: 'NN15 7QX',
  },
  'kings-lynn-and-west-norfolk': {
    formalName: 'Borough Council of King\'s Lynn & West Norfolk',
    department: 'Parking Operations Department',
    addressLine1: 'PO Box 1149',
    city: 'King\'s Lynn',
    postcode: 'PE30 9AH',
  },
  'kingston-upon-hull-city-of': {
    formalName: 'Hull City Council',
    department: 'Parking Services',
    addressLine1: 'The Guildhall',
    addressLine2: 'Alfred Gelder Street',
    city: 'Hull',
    postcode: 'HU1 2AA',
  },
  'kingston-upon-thames': {
    formalName: 'Royal Borough of Kingston upon Thames',
    department: 'Parking Services',
    addressLine1: 'Guildhall',
    addressLine2: 'High Street',
    city: 'Kingston upon Thames',
    postcode: 'KT1 1EU',
  },
  'kirklees': {
    formalName: 'Kirklees Council',
    department: 'Parking Office',
    addressLine1: 'PO Box 1720',
    city: 'Huddersfield',
    postcode: 'HD1 9EL',
  },
  'knowsley': {
    formalName: 'Knowsley Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Buildings',
    addressLine2: 'Cherryfield Drive',
    city: 'Kirkby',
    postcode: 'L32 1TX',
  },
  'lambeth': {
    formalName: 'London Borough of Lambeth',
    department: 'Lambeth Parking Services',
    addressLine1: 'PO Box 4525',
    city: 'Worthing',
    postcode: 'BN13 1XT',
  },
  'lancaster': {
    formalName: 'Lancashire Parking Services',
    department: 'Parking Services',
    addressLine1: 'PO Box 1023',
    city: 'Preston',
    postcode: 'PR1 3ZA',
  },
  'leeds': {
    formalName: 'Leeds City Council',
    department: 'Parking Services',
    addressLine1: 'P.O. Box 139',
    city: 'Leeds',
    postcode: 'LS9 1AA',
  },
  'leicester': {
    formalName: 'Leicester City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 8459',
    city: 'Leicester',
    postcode: 'LE1 8AW',
  },
  'lewes': {
    formalName: 'Lewes District Council',
    department: 'Parking Services',
    addressLine1: 'Southover House',
    addressLine2: 'Southover Road',
    city: 'Lewes',
    postcode: 'BN7 1AB',
  },
  'lewisham': {
    formalName: 'London Borough of Lewisham',
    department: 'Parking Services',
    addressLine1: 'Laurence House',
    addressLine2: '1 Catford Road',
    city: 'London',
    postcode: 'SE6 4RU',
  },
  'lichfield': {
    formalName: 'Lichfield District Council',
    department: 'Parking Services',
    addressLine1: 'District Council House',
    city: 'Lichfield',
    postcode: 'WS13 6HP',
  },
  'lincoln': {
    formalName: 'City of Lincoln Council',
    department: 'Parking Services',
    addressLine1: 'City Hall',
    addressLine2: 'Beaumont Fee',
    city: 'Lincoln',
    postcode: 'LN1 1DD',
  },
  'liverpool': {
    formalName: 'Liverpool City Council',
    department: 'Parking Services',
    addressLine1: 'Cunard Building, Water Street',
    city: 'Liverpool',
    postcode: 'L3 1DS',
  },
  'luton': {
    formalName: 'Luton Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    city: 'Luton',
    postcode: 'LU1 2BQ',
  },
  'maidstone': {
    formalName: 'Maidstone Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 249',
    city: 'Maidstone',
    postcode: 'ME16 8BQ',
  },
  'maldon': {
    formalName: 'Maldon District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices',
    addressLine2: 'Princes Road',
    city: 'Maldon',
    postcode: 'CM9 5DL',
  },
  'malvern-hills': {
    formalName: 'Malvern Hills District Council',
    department: 'Parking Services Unit, Wychavon District Council',
    addressLine1: 'Civic Centre',
    addressLine2: 'Queen Elizabeth Drive, Pershore',
    city: 'Pershore',
    postcode: 'WR10 1PT',
  },
  'manchester': {
    formalName: 'Manchester City Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall Extension',
    addressLine2: 'Albert Square',
    city: 'Manchester',
    postcode: 'M60 2LA',
  },
  'mansfield': {
    formalName: 'Mansfield District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Chesterfield Road South',
    city: 'Mansfield',
    postcode: 'NG19 7BH',
  },
  'medway': {
    formalName: 'Medway Council',
    department: 'Parking Services',
    addressLine1: 'Gun Wharf',
    addressLine2: 'Dock Road',
    city: 'Chatham',
    postcode: 'ME4 4TR',
  },
  'melton': {
    formalName: 'Melton Borough Council',
    department: 'Parking Services',
    addressLine1: 'Parkside, Station Approach, Burton Street',
    city: 'Melton Mowbray',
    postcode: 'LE13 1GH',
  },
  'mendip': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'Cannards Grave Road',
    city: 'Shepton Mallet',
    postcode: 'BA4 5BT',
  },
  'merton': {
    formalName: 'London Borough of Merton',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, London Road',
    city: 'Morden',
    postcode: 'SM4 5DX',
  },
  'mid-devon': {
    formalName: 'Mid Devon District Council',
    department: 'Parking Services',
    addressLine1: 'Phoenix House, Phoenix Lane',
    city: 'Tiverton',
    postcode: 'EX16 6PP',
  },
  'mid-suffolk': {
    formalName: 'Mid Suffolk District Council',
    department: 'Parking Services',
    addressLine1: 'Endeavour House',
    addressLine2: '8 Russell Road',
    city: 'Ipswich',
    postcode: 'IP1 2BX',
  },
  'mid-sussex': {
    formalName: 'Mid Sussex District Council',
    department: 'Parking Services',
    addressLine1: 'Oaklands',
    addressLine2: 'Oaklands Road',
    city: 'Haywards Heath',
    postcode: 'RH16 1SS',
  },
  'middlesbrough': {
    formalName: 'Middlesbrough Council',
    department: 'Parking Services',
    addressLine1: 'Middlesbrough House, 50 Corporation Road',
    city: 'Middlesbrough',
    postcode: 'TS1 2YQ',
  },
  'milton-keynes': {
    formalName: 'Milton Keynes City Council',
    department: 'Parking Services',
    addressLine1: 'Civic, 1 Saxon Gate East',
    addressLine2: 'Central Milton Keynes',
    city: 'Milton Keynes',
    postcode: 'MK9 3EJ',
  },
  'mole-valley': {
    formalName: 'Mole Valley District Council',
    department: 'Parking Services',
    addressLine1: 'Pippbrook',
    city: 'Dorking',
    postcode: 'RH4 1SJ',
  },
  'new-forest': {
    formalName: 'New Forest District Council',
    department: 'Parking Services',
    addressLine1: 'Appletree Court, Beaulieu Road',
    city: 'Lyndhurst',
    postcode: 'SO43 7PA',
  },
  'newark-and-sherwood': {
    formalName: 'Newark and Sherwood District Council',
    department: 'Parking Services',
    addressLine1: 'Castle House',
    addressLine2: 'Great North Road',
    city: 'Newark',
    postcode: 'NG24 1BY',
  },
  'newcastle-under-lyme': {
    formalName: 'Newcastle-under-Lyme Borough Council',
    department: 'Parking Services',
    addressLine1: 'Castle House',
    addressLine2: 'Barracks Road',
    city: 'Newcastle-under-Lyme',
    postcode: 'ST5 1BL',
  },
  'newcastle-upon-tyne': {
    formalName: 'Newcastle City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 2BL',
    city: 'Newcastle Upon Tyne',
    postcode: 'NE99 2BL',
  },
  'newham': {
    formalName: 'London Borough of Newham',
    department: 'Parking Services',
    addressLine1: 'PO Box 14460',
    city: 'London',
    postcode: 'E6 9AF',
  },
  'north-devon': {
    formalName: 'North Devon Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 240',
    city: 'Barnstaple',
    postcode: 'EX32 0GQ',
  },
  'north-dorset': {
    formalName: 'Dorset Council',
    department: 'Parking Services',
    addressLine1: 'Charminster Depot, Wanchard Lane',
    addressLine2: 'Charminster',
    city: 'Dorchester',
    postcode: 'DT2 9RP',
  },
  'north-east-derbyshire': {
    formalName: 'North East Derbyshire District Council',
    department: 'Parking Services',
    addressLine1: '2013 Mill Lane',
    addressLine2: 'Wingerworth',
    city: 'Chesterfield',
    postcode: 'S42 6NG',
  },
  'north-east-lincolnshire': {
    formalName: 'North East Lincolnshire Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 493',
    city: 'Grimsby',
    postcode: 'DN31 1HU',
  },
  'north-hertfordshire': {
    formalName: 'North Hertfordshire District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 10613',
    city: 'Nottingham',
    postcode: 'NG6 6DW',
  },
  'north-kesteven': {
    formalName: 'North Kesteven District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 3',
    addressLine2: 'Kesteven Street',
    city: 'Sleaford',
    postcode: 'NG34 7EF',
  },
  'north-lincolnshire': {
    formalName: 'North Lincolnshire Council',
    department: 'Parking Services',
    addressLine1: 'Church Square House',
    addressLine2: 'PO Box 42',
    city: 'Scunthorpe',
    postcode: 'DN15 6XQ',
  },
  'north-norfolk': {
    formalName: 'North Norfolk District Council',
    department: 'Parking Operations Department',
    addressLine1: 'PO Box 1149',
    city: 'King\'s Lynn',
    postcode: 'PE30 9AH',
  },
  'north-northamptonshire': {
    formalName: 'North Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Offices',
    addressLine2: 'Bowling Green Road',
    city: 'Kettering',
    postcode: 'NN15 7QX',
  },
  'north-somerset': {
    formalName: 'North Somerset Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Walliscote Grove Road',
    city: 'Weston-super-Mare',
    postcode: 'BS23 1UJ',
  },
  'north-tyneside': {
    formalName: 'North Tyneside Council',
    department: 'Parking Services',
    addressLine1: 'Quadrant, The Silverlink North',
    addressLine2: 'Cobalt Business Park',
    city: 'North Shields',
    postcode: 'NE27 0BY',
  },
  'north-warwickshire': {
    formalName: 'North Warwickshire Borough Council',
    department: 'Parking Services',
    addressLine1: 'The Council House',
    addressLine2: 'South Street',
    city: 'Atherstone',
    postcode: 'CV9 1DE',
  },
  'north-west-leicestershire': {
    formalName: 'North West Leicestershire District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices',
    addressLine2: 'Whitwick Road',
    city: 'Coalville',
    postcode: 'LE67 3FJ',
  },
  'north-yorkshire': {
    formalName: 'North Yorkshire Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, Racecourse Lane',
    city: 'Northallerton',
    postcode: 'DL7 8AD',
  },
  'northampton': {
    formalName: 'West Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'One Angel Square, Angel Street',
    city: 'Northampton',
    postcode: 'NN1 1ED',
  },
  'northumberland': {
    formalName: 'Northumberland County Council',
    department: 'Parking Services',
    addressLine1: 'County Hall',
    city: 'Morpeth',
    postcode: 'NE61 2EF',
  },
  'norwich': {
    formalName: 'Norwich City Council',
    department: 'Parking Operations',
    addressLine1: 'City Hall, St Peters Street',
    city: 'Norwich',
    postcode: 'NR2 1NH',
  },
  'nottingham': {
    formalName: 'Nottingham City Council',
    department: 'Parking Regulation and Compliance',
    addressLine1: 'PO Box 10169',
    city: 'Nottingham',
    postcode: 'NG1 9HS',
  },
  'nuneaton-and-bedworth': {
    formalName: 'Nuneaton and Bedworth Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Coton Road',
    city: 'Nuneaton',
    postcode: 'CV11 5AA',
  },
  'oadby-and-wigston': {
    formalName: 'Oadby and Wigston Borough Council',
    department: 'Parking Services',
    addressLine1: 'Brocks Hill Council Offices',
    addressLine2: 'Washbrook Lane, Oadby',
    city: 'Leicester',
    postcode: 'LE2 5JJ',
  },
  'oldham': {
    formalName: 'Oldham Council',
    department: 'Parking Shop',
    addressLine1: 'PO Box 499',
    city: 'Oldham',
    postcode: 'OL1 9AA',
  },
  'oxford': {
    formalName: 'Oxfordshire County Council',
    department: 'Civil Enforcement Team',
    addressLine1: 'Ron Groves House, 23 Oxford Road',
    city: 'Kidlington',
    postcode: 'OX5 2BP',
  },
  'parkingEye': {
    formalName: 'Parkingeye Limited',
    department: 'Penalty Charge Notice Department',
    addressLine1: 'PO Box 117',
    city: 'Blyth',
    postcode: 'NE24 9EJ',
  },
  'pendle': {
    formalName: 'Pendle Borough Council',
    department: 'Parking Services',
    addressLine1: 'Number One Market Street',
    city: 'Nelson',
    postcode: 'BB9 7LJ',
  },
  'peterborough': {
    formalName: 'Peterborough City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 1077',
    city: 'Peterborough',
    postcode: 'PE1 9JR',
  },
  'plymouth': {
    formalName: 'Plymouth City Council',
    department: 'Parking Services',
    addressLine1: 'Ground Floor Civic Centre',
    city: 'Plymouth',
    postcode: 'PL1 2AA',
  },
  'poole': {
    formalName: 'Bournemouth, Christchurch & Poole Council',
    department: 'Parking Administration',
    addressLine1: 'BCP Council Civic Centre',
    addressLine2: 'Bourne Avenue',
    city: 'Bournemouth',
    postcode: 'BH2 6DY',
  },
  'portsmouth': {
    formalName: 'Portsmouth City Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices, Guildhall Square',
    city: 'Portsmouth',
    postcode: 'PO1 2AL',
  },
  'preston': {
    formalName: 'Preston City Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall, Lancaster Road',
    city: 'Preston',
    postcode: 'PR1 2RL',
  },
  'purbeck': {
    formalName: 'Dorset Council',
    department: 'Parking Services',
    addressLine1: 'Unit 6 Kings Court',
    addressLine2: 'Kings Road West',
    city: 'Swanage',
    postcode: 'BH19 1JU',
  },
  'reading': {
    formalName: 'Reading Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices, Bridge Street',
    city: 'Reading',
    postcode: 'RG1 2LU',
  },
  'redbridge': {
    formalName: 'London Borough of Redbridge',
    department: 'Parking Services',
    addressLine1: '531 Ley Street',
    addressLine2: 'Council Offices',
    city: 'Ilford',
    postcode: 'IG2 7QZ',
  },
  'redcar-and-cleveland': {
    formalName: 'Redcar and Cleveland Borough Council',
    department: 'Parking Services',
    addressLine1: 'Redcar and Cleveland House',
    addressLine2: 'Kirkleatham Street',
    city: 'Redcar',
    postcode: 'TS10 1RT',
  },
  'redditch': {
    formalName: 'Redditch Borough Council',
    department: 'Parking Services Unit',
    addressLine1: 'Civic Centre, Queen Elizabeth Drive',
    city: 'Pershore',
    postcode: 'WR10 1PT',
  },
  'reigate-and-banstead': {
    formalName: 'Reigate & Banstead Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 527',
    city: 'Redhill',
    postcode: 'RH1 6YT',
  },
  'ribble-valley': {
    formalName: 'Ribble Valley Borough Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, Church Walk',
    city: 'Clitheroe',
    postcode: 'BB7 2RA',
  },
  'richmond-upon-thames': {
    formalName: 'London Borough of Richmond upon Thames',
    department: 'Parking Services',
    addressLine1: 'P.O. Box 221',
    city: 'Twickenham',
    postcode: 'TW1 3TL',
  },
  'richmondshire': {
    formalName: 'Richmondshire District Council',
    department: 'Parking Services',
    addressLine1: 'Mercury House, Station Road',
    city: 'Richmond',
    postcode: 'DL10 4JX',
  },
  'rochdale': {
    formalName: 'Rochdale Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 50',
    city: 'Rochdale',
    postcode: 'OL16 1FL',
  },
  'rochford': {
    formalName: 'Rochford District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Suite, 2 Hockley Road',
    city: 'Rayleigh',
    postcode: 'SS6 8EB',
  },
  'rossendale': {
    formalName: 'Rossendale Borough Council',
    department: 'Parking Services',
    addressLine1: 'The Business Centre, Futures Park',
    city: 'Bacup',
    postcode: 'OL13 0BB',
  },
  'rother': {
    formalName: 'Rother District Council',
    department: 'Car Park Administration Team',
    addressLine1: 'Town Hall',
    city: 'Bexhill-on-Sea',
    postcode: 'TN39 3JX',
  },
  'rotherham': {
    formalName: 'Rotherham Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Riverside House, Main Street',
    city: 'Rotherham',
    postcode: 'S60 1AE',
  },
  'rugby': {
    formalName: 'Rugby Borough Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Evreux Way',
    city: 'Rugby',
    postcode: 'CV21 2RR',
  },
  'runnymede': {
    formalName: 'Runnymede Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Station Road',
    city: 'Addlestone',
    postcode: 'KT15 2AH',
  },
  'rushcliffe': {
    formalName: 'Rushcliffe Borough Council',
    department: 'Parking Services',
    addressLine1: 'Rushcliffe Arena, Rugby Road',
    city: 'West Bridgford',
    postcode: 'NG2 7YG',
  },
  'rushmoor': {
    formalName: 'Rushmoor Borough Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, Farnborough Road',
    city: 'Farnborough',
    postcode: 'GU14 7JU',
  },
  'rutland': {
    formalName: 'Rutland County Council',
    department: 'Parking Services',
    addressLine1: 'Catmose',
    city: 'Oakham',
    postcode: 'LE15 6HP',
  },
  'ryedale': {
    formalName: 'North Yorkshire Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, Racecourse Lane',
    city: 'Northallerton',
    postcode: 'DL7 8AD',
  },
  'salford': {
    formalName: 'Salford City Council',
    department: 'Parking Services',
    addressLine1: 'Technical Services, Salford Civic Centre, Chorley Road',
    addressLine2: 'Swinton',
    city: 'Salford',
    postcode: 'M27 5AS',
  },
  'sandwell': {
    formalName: 'Sandwell Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Sandwell Council House, Freeth Street',
    city: 'Oldbury',
    postcode: 'B69 3DB',
  },
  'scarborough': {
    formalName: 'North Yorkshire Council',
    department: 'Parking Services',
    addressLine1: 'County Hall',
    addressLine2: 'Racecourse Lane',
    city: 'Northallerton',
    postcode: 'DL7 8AL',
  },
  'sedgemoor': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'Bridgwater House',
    addressLine2: 'King Square',
    city: 'Bridgwater',
    postcode: 'TA6 3AR',
  },
  'sefton': {
    formalName: 'Sefton Council',
    department: 'Parking Services',
    addressLine1: '324 Stanley Road',
    addressLine2: 'Bootle One Stop Shop',
    city: 'Bootle',
    postcode: 'L20 3ET',
  },
  'selby': {
    formalName: 'North Yorkshire Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 283',
    city: 'Northallerton',
    postcode: 'DL7 8FF',
  },
  'sevenoaks': {
    formalName: 'Sevenoaks District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, Argyle Road',
    city: 'Sevenoaks',
    postcode: 'TN13 1HG',
  },
  'sheffield': {
    formalName: 'Sheffield City Council',
    department: 'Parking Services',
    addressLine1: 'Howden House',
    addressLine2: '1 Union Street',
    city: 'Sheffield',
    postcode: 'S1 2SH',
  },
  'shropshire': {
    formalName: 'Shropshire Council',
    department: 'Parking Services',
    addressLine1: 'Shirehall',
    addressLine2: 'Abbey Foregate',
    city: 'Shrewsbury',
    postcode: 'SY2 6ND',
  },
  'slough': {
    formalName: 'Slough Borough Council',
    department: 'Parking Services',
    addressLine1: 'Observatory House',
    addressLine2: '25 Windsor Road',
    city: 'Slough',
    postcode: 'SL1 2EL',
  },
  'solihull': {
    formalName: 'Solihull Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Council House, Manor Square',
    city: 'Solihull',
    postcode: 'B91 3QB',
  },
  'somerset': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, The Crescent',
    city: 'Taunton',
    postcode: 'TA1 4DY',
  },
  'somerset-west-and-taunton': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'County Hall',
    city: 'Taunton',
    postcode: 'TA1 4DY',
  },
  'south-bucks': {
    formalName: 'Buckinghamshire Council',
    department: 'Parking Services Team',
    addressLine1: 'Walton Street Office, Walton Street',
    city: 'Aylesbury',
    postcode: 'HP20 1UA',
  },
  'south-cambridgeshire': {
    formalName: 'Cambridgeshire County Council',
    department: 'Parking Permits',
    addressLine1: 'PO Box 761',
    city: 'Huntingdon',
    postcode: 'PE29 9QR',
  },
  'south-derbyshire': {
    formalName: 'South Derbyshire District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices, Civic Way',
    city: 'Swadlincote',
    postcode: 'DE11 0AH',
  },
  'south-gloucestershire': {
    formalName: 'South Gloucestershire Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 1954',
    city: 'Bristol',
    postcode: 'BS37 0DD',
  },
  'south-hams': {
    formalName: 'South Hams District Council',
    department: 'Parking Services',
    addressLine1: 'Follaton House, Plymouth Road',
    city: 'Totnes',
    postcode: 'TQ9 5NE',
  },
  'south-holland': {
    formalName: 'South Holland District Council',
    department: 'Parking Services',
    addressLine1: 'Priory Road',
    city: 'Spalding',
    postcode: 'PE11 2XE',
  },
  'south-kesteven': {
    formalName: 'South Kesteven District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices',
    addressLine2: 'The Picture House, St Catherines Road',
    city: 'Grantham',
    postcode: 'NG31 6TT',
  },
  'south-lakeland': {
    formalName: 'Westmorland and Furness Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 304',
    city: 'Kendal',
    postcode: 'LA9 9GY',
  },
  'south-norfolk': {
    formalName: 'South Norfolk Council',
    department: 'Parking Services',
    addressLine1: 'The Horizon Centre, Peachman Way, Broadland Business Park',
    city: 'Norwich',
    postcode: 'NR7 0WF',
  },
  'south-northamptonshire': {
    formalName: 'West Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'The Guildhall',
    addressLine2: 'St Giles Square',
    city: 'Northampton',
    postcode: 'NN1 1DE',
  },
  'south-oxfordshire': {
    formalName: 'South Oxfordshire District Council',
    department: 'Parking Services',
    addressLine1: 'Abbey House',
    addressLine2: 'Abbey Close',
    city: 'Abingdon',
    postcode: 'OX14 3JE',
  },
  'south-ribble': {
    formalName: 'South Ribble Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, West Paddock',
    city: 'Leyland',
    postcode: 'PR25 1DH',
  },
  'south-somerset': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'Box Factory',
    addressLine2: '42 South Street',
    city: 'Yeovil',
    postcode: 'BA20 1NN',
  },
  'south-staffordshire': {
    formalName: 'South Staffordshire District Council',
    department: 'Parking Services',
    addressLine1: 'Wolverhampton Road',
    city: 'Codsall',
    postcode: 'WV8 1PX',
  },
  'south-tyneside': {
    formalName: 'South Tyneside Council',
    department: 'Parking Services',
    addressLine1: 'Town Hall and Civic Offices, Westoe Road',
    city: 'South Shields',
    postcode: 'NE33 2RL',
  },
  'southampton': {
    formalName: 'Southampton City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 663',
    city: 'Southampton',
    postcode: 'SO14 9SJ',
  },
  'southend-on-sea': {
    formalName: 'Southend-on-Sea City Council',
    department: 'Parking, Highways, and Transport',
    addressLine1: 'Civic Centre',
    addressLine2: 'Victoria Avenue',
    city: 'Southend-on-Sea',
    postcode: 'SS1 9SB',
  },
  'southwark': {
    formalName: 'London Borough of Southwark',
    department: 'Parking Services',
    addressLine1: '160 Tooley Street',
    city: 'London',
    postcode: 'SE1 2QH',
  },
  'spelthorne': {
    formalName: 'Spelthorne Borough Council',
    department: 'Parking Services',
    addressLine1: 'Knowle Green',
    city: 'Staines-upon-Thames',
    postcode: 'TW18 1XB',
  },
  'st-albans': {
    formalName: 'St Albans City and District Council',
    department: 'Parking Services',
    addressLine1: 'St Peter\'s Street',
    city: 'St Albans',
    postcode: 'AL1 3JE',
  },
  'st-edmundsbury': {
    formalName: 'West Suffolk Council',
    department: 'Parking Services',
    addressLine1: 'West Suffolk House, Western Way',
    city: 'Bury St Edmunds',
    postcode: 'IP33 3YU',
  },
  'st-helens': {
    formalName: 'St Helens Borough Council',
    department: 'Parking Services',
    addressLine1: 'Contact Centre, Wesley House, Corporation Street',
    city: 'St Helens',
    postcode: 'WA10 1HF',
  },
  'stafford': {
    formalName: 'Stafford Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Riverside',
    city: 'Stafford',
    postcode: 'ST16 3AQ',
  },
  'staffordshire-moorlands': {
    formalName: 'Staffordshire Moorlands District Council',
    department: 'Parking Services',
    addressLine1: 'Moorlands House, Stockwell Street',
    city: 'Leek',
    postcode: 'ST13 6HQ',
  },
  'stevenage': {
    formalName: 'Stevenage Borough Council',
    department: 'Parking Services',
    addressLine1: 'Daneshill House, Danestrete',
    city: 'Stevenage',
    postcode: 'SG1 1HN',
  },
  'stockport': {
    formalName: 'Stockport Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Stopford House',
    addressLine2: 'Piccadilly',
    city: 'Stockport',
    postcode: 'SK1 3XE',
  },
  'stockton-on-tees': {
    formalName: 'Stockton-on-Tees Borough Council',
    department: 'Parking Services',
    addressLine1: 'Municipal Buildings, Church Road',
    city: 'Stockton-on-Tees',
    postcode: 'TS18 1LD',
  },
  'stoke-on-trent': {
    formalName: 'Stoke-on-Trent City Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 4907',
    city: 'Stoke-on-Trent',
    postcode: 'ST6 9FU',
  },
  'stratford-on-avon': {
    formalName: 'Stratford-on-Avon District Council',
    department: 'Parking Services',
    addressLine1: 'Elizabeth House, Church Street',
    city: 'Stratford-upon-Avon',
    postcode: 'CV37 6HX',
  },
  'stroud': {
    formalName: 'Stroud District Council',
    department: 'Parking Services',
    addressLine1: 'Ebley Mill, Westward Road',
    city: 'Stroud',
    postcode: 'GL5 4UB',
  },
  'suffolk-coastal': {
    formalName: 'East Suffolk Council',
    department: 'Parking Services',
    addressLine1: 'East Suffolk House',
    addressLine2: 'Station Road, Melton',
    city: 'Woodbridge',
    postcode: 'IP12 1RT',
  },
  'sunderland': {
    formalName: 'Sunderland City Council',
    department: 'Parking Services',
    addressLine1: 'Wellington Lane',
    city: 'Sunderland',
    postcode: 'SR4 6DA',
  },
  'surrey-heath': {
    formalName: 'Surrey Heath Borough Council',
    department: 'Parking Services',
    addressLine1: 'Surrey Heath House',
    addressLine2: 'Knoll Road',
    city: 'Camberley',
    postcode: 'GU15 3HD',
  },
  'sutton': {
    formalName: 'London Borough of Sutton',
    department: 'Parking Services',
    addressLine1: 'Civic Offices, St Nicholas Way',
    city: 'Sutton',
    postcode: 'SM1 1EA',
  },
  'swale': {
    formalName: 'Swale Borough Council',
    department: 'Parking Services',
    addressLine1: 'Swale House',
    addressLine2: 'East Street',
    city: 'Sittingbourne',
    postcode: 'ME10 3HT',
  },
  'swindon': {
    formalName: 'Swindon Borough Council',
    department: 'WCP Parking Services',
    addressLine1: 'Civic Offices',
    addressLine2: 'Euclid Street',
    city: 'Swindon',
    postcode: 'SN1 2JH',
  },
  'tameside': {
    formalName: 'Tameside Metropolitan Borough Council',
    department: 'Parking Services',
    addressLine1: 'Tame Street Depot, Tame Street',
    city: 'Stalybridge',
    postcode: 'SK15 1ST',
  },
  'tamworth': {
    formalName: 'Tamworth Borough Council',
    department: 'Parking Services',
    addressLine1: 'Marmion House, Lichfield Street',
    city: 'Tamworth',
    postcode: 'B79 7BZ',
  },
  'tandridge': {
    formalName: 'Tandridge District Council',
    department: 'Parking Services',
    addressLine1: '8 Station Road East',
    city: 'Oxted',
    postcode: 'RH8 0BT',
  },
  'taunton-deane': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 444',
    city: 'Taunton',
    postcode: 'TA1 9BL',
  },
  'teignbridge': {
    formalName: 'Teignbridge District Council',
    department: 'Parking Services',
    addressLine1: 'Forde House, Brunel Road',
    city: 'Newton Abbot',
    postcode: 'TQ12 4XX',
  },
  'telford-and-wrekin': {
    formalName: 'Telford & Wrekin Council',
    department: 'Parking Services',
    addressLine1: 'Addenbrooke House',
    addressLine2: 'Ironmasters Way',
    city: 'Telford',
    postcode: 'TF3 4NT',
  },
  'tendring': {
    formalName: 'Tendring District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 8259',
    city: 'Clacton-On-Sea',
    postcode: 'CO15 6AY',
  },
  'test-valley': {
    formalName: 'Test Valley Borough Council',
    department: 'Parking Services',
    addressLine1: 'Beech Hurst',
    city: 'Andover',
    postcode: 'SP10 3AJ',
  },
  'tewkesbury': {
    formalName: 'Tewkesbury Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 3584',
    city: 'Chippenham',
    postcode: 'SN15 9EF',
  },
  'tfl': {
    formalName: 'London Councils',
    department: 'Parking Services',
    addressLine1: '59½ Southwark Street',
    city: 'London',
    postcode: 'SE1 0AL',
  },
  'thanet': {
    formalName: 'Thanet District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 9, Cecil Street',
    city: 'Margate',
    postcode: 'CT9 1XZ',
  },
  'three-rivers': {
    formalName: 'Three Rivers District Council',
    department: 'Parking Services',
    addressLine1: 'Three Rivers House',
    addressLine2: 'Northway',
    city: 'Rickmansworth',
    postcode: 'WD3 1RL',
  },
  'thurrock': {
    formalName: 'Thurrock Council',
    department: 'Parking Enforcement',
    addressLine1: 'Civic Offices',
    addressLine2: 'New Road',
    city: 'Grays',
    postcode: 'RM17 6SL',
  },
  'tonbridge-and-malling': {
    formalName: 'Tonbridge and Malling Borough Council',
    department: 'Financial Services',
    addressLine1: 'Gibson Drive, Kings Hill',
    city: 'West Malling',
    postcode: 'ME19 4LZ',
  },
  'torbay': {
    formalName: 'Torbay Council',
    department: 'Exchequer Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Castle Circus',
    city: 'Torquay',
    postcode: 'TQ1 3DR',
  },
  'torridge': {
    formalName: 'Torridge District Council',
    department: 'Parking Services',
    addressLine1: 'Riverbank House',
    city: 'Bideford',
    postcode: 'EX39 2QG',
  },
  'tower-hamlets': {
    formalName: 'London Borough of Tower Hamlets',
    department: 'Parking Services',
    addressLine1: 'Tower Hamlets Town Hall',
    addressLine2: '160 Whitechapel Road',
    city: 'London',
    postcode: 'E1 1BJ',
  },
  'trafford': {
    formalName: 'Trafford Council',
    department: 'Parking Services',
    addressLine1: 'Trafford Town Hall',
    addressLine2: 'Talbot Road',
    city: 'Stretford',
    postcode: 'M32 0TH',
  },
  'tunbridge-wells': {
    formalName: 'Tunbridge Wells Borough Council',
    department: 'Parking Manager',
    addressLine1: 'Town Hall',
    city: 'Royal Tunbridge Wells',
    postcode: 'TN1 1RS',
  },
  'uttlesford': {
    formalName: 'Uttlesford District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, London Road',
    city: 'Saffron Walden',
    postcode: 'CB11 4ER',
  },
  'vale-of-white-horse': {
    formalName: 'Vale of White Horse District Council',
    department: 'Parking Services',
    addressLine1: 'Abbey House',
    addressLine2: 'Abbey Close',
    city: 'Abingdon',
    postcode: 'OX14 3JE',
  },
  'wakefield': {
    formalName: 'Wakefield Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 47',
    city: 'Wakefield',
    postcode: 'WF1 2QW',
  },
  'walsall': {
    formalName: 'Walsall Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Darwall Street',
    city: 'Walsall',
    postcode: 'WS1 1TP',
  },
  'waltham-forest': {
    formalName: 'London Borough of Waltham Forest',
    department: 'Parking Services Permit Team',
    addressLine1: 'PO Box 74924',
    city: 'London',
    postcode: 'E17 0UG',
  },
  'wandsworth': {
    formalName: 'Wandsworth Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 521',
    city: 'Twickenham',
    postcode: 'TW1 9PJ',
  },
  'warrington': {
    formalName: 'Warrington Borough Council',
    department: 'Parking Services',
    addressLine1: '3rd Floor, New Town House',
    city: 'Warrington',
    postcode: 'WA1 2NH',
  },
  'warwick': {
    formalName: 'Warwick District Council',
    department: 'Contract Services',
    addressLine1: 'Town Hall',
    addressLine2: 'Parade',
    city: 'Royal Leamington Spa',
    postcode: 'CV32 4AT',
  },
  'watford': {
    formalName: 'Watford Borough Council',
    department: 'Parking Services',
    addressLine1: '71-73 Market Street',
    city: 'Watford',
    postcode: 'WD18 0PS',
  },
  'waveney': {
    formalName: 'East Suffolk Council',
    department: 'Parking Services',
    addressLine1: 'Riverside',
    addressLine2: '4 Canning Road',
    city: 'Lowestoft',
    postcode: 'NR33 0EQ',
  },
  'waverley': {
    formalName: 'Waverley Borough Council',
    department: 'Parking Services',
    addressLine1: 'The Burys',
    city: 'Godalming',
    postcode: 'GU7 1HR',
  },
  'wealden': {
    formalName: 'Wealden District Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, Vicarage Lane',
    city: 'Hailsham',
    postcode: 'BN27 2AX',
  },
  'wellingborough': {
    formalName: 'North Northamptonshire Council',
    department: 'Parking Services',
    addressLine1: 'Sheerness House',
    addressLine2: '41 Meadow Road',
    city: 'Kettering',
    postcode: 'NN16 8TL',
  },
  'welwyn-hatfield': {
    formalName: 'Welwyn Hatfield Borough Council',
    department: 'Parking Services',
    addressLine1: 'Council Offices, The Campus',
    city: 'Welwyn Garden City',
    postcode: 'AL8 6AE',
  },
  'west-berkshire': {
    formalName: 'West Berkshire Council',
    department: 'The Parking Office',
    addressLine1: 'Council Offices',
    addressLine2: 'Market Street',
    city: 'Newbury',
    postcode: 'RG14 5LD',
  },
  'west-devon': {
    formalName: 'West Devon Borough Council',
    department: 'Parking Services',
    addressLine1: 'Kilworthy Park',
    city: 'Tavistock',
    postcode: 'PL19 0JZ',
  },
  'west-dorset': {
    formalName: 'Dorset Council',
    department: 'Parking Services',
    addressLine1: 'Charminster Depot, Wanchard Lane',
    city: 'Dorchester',
    postcode: 'DT2 9RP',
  },
  'west-lancashire': {
    formalName: 'West Lancashire Borough Council',
    department: 'Parking Services',
    addressLine1: '52 Derby Street',
    city: 'Ormskirk',
    postcode: 'L39 2DF',
  },
  'west-lindsey': {
    formalName: 'West Lindsey District Council',
    department: 'Parking Services',
    addressLine1: 'Guildhall, Marshall\'s Yard',
    city: 'Gainsborough',
    postcode: 'DN21 2NA',
  },
  'west-northamptonshire': {
    formalName: 'West Northamptonshire Council',
    department: 'Traffic Enforcement Team',
    addressLine1: 'One Angel Square (Service Yard)',
    addressLine2: 'Angel Street',
    city: 'Northampton',
    postcode: 'NN1 1ED',
  },
  'west-oxfordshire': {
    formalName: 'West Oxfordshire District Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 335',
    city: 'Cirencester',
    postcode: 'GL7 9JH',
  },
  'west-somerset': {
    formalName: 'Somerset Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, The Crescent',
    city: 'Taunton',
    postcode: 'TA1 4DY',
  },
  'west-suffolk': {
    formalName: 'West Suffolk Council',
    department: 'Parking Services',
    addressLine1: 'West Suffolk House',
    addressLine2: 'Western Way',
    city: 'Bury St Edmunds',
    postcode: 'IP33 3YU',
  },
  'westminster': {
    formalName: 'Westminster City Council',
    department: 'Parking Services',
    addressLine1: '5 Strand',
    city: 'London',
    postcode: 'WC2N 5HR',
  },
  'westmorland-and-furness': {
    formalName: 'Westmorland and Furness Council',
    department: 'Parking Services',
    addressLine1: 'South Lakeland House, Lowther Street',
    city: 'Kendal',
    postcode: 'LA9 4DQ',
  },
  'weymouth-and-portland': {
    formalName: 'Dorset Council',
    department: 'Parking Services',
    addressLine1: 'County Hall, Colliton Park',
    city: 'Dorchester',
    postcode: 'DT1 1XJ',
  },
  'wigan': {
    formalName: 'Wigan Council',
    department: 'Parking Services',
    addressLine1: 'Wigan Life Centre, College Avenue',
    city: 'Wigan',
    postcode: 'WN1 1YN',
  },
  'wiltshire': {
    formalName: 'Wiltshire Council',
    department: 'Parking Services',
    addressLine1: 'County Hall',
    city: 'Trowbridge',
    postcode: 'BA14 8JN',
  },
  'winchester': {
    formalName: 'Winchester City Council',
    department: 'Parking Services',
    addressLine1: 'City Offices',
    addressLine2: 'Colebrook Street',
    city: 'Winchester',
    postcode: 'SO23 9LJ',
  },
  'windsor-and-maidenhead': {
    formalName: 'Royal Borough of Windsor and Maidenhead',
    department: 'Parking Team',
    addressLine1: 'Town Hall',
    addressLine2: 'St Ives Road',
    city: 'Maidenhead',
    postcode: 'SL6 1RF',
  },
  'wirral': {
    formalName: 'Wirral Borough Council',
    department: 'Parking Services',
    addressLine1: 'PO Box 285',
    city: 'Sheffield',
    postcode: 'S98 1RW',
  },
  'woking': {
    formalName: 'Woking Borough Council',
    department: 'Parking Services',
    addressLine1: 'Civic Offices Gloucester Square',
    city: 'Woking',
    postcode: 'GU21 6YL',
  },
  'wokingham': {
    formalName: 'Wokingham Borough Council',
    department: 'Parking Services',
    addressLine1: 'Shute End',
    addressLine2: 'Biscoe Way',
    city: 'Wokingham',
    postcode: 'RG40 1BN',
  },
  'wolverhampton': {
    formalName: 'City of Wolverhampton Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, St. Peter\'s Square',
    city: 'Wolverhampton',
    postcode: 'WV1 1SH',
  },
  'worcester': {
    formalName: 'Worcester City Council',
    department: 'Parking Services',
    addressLine1: 'Customer Service Centre, The Guildhall, High Street',
    city: 'Worcester',
    postcode: 'WR1 2EY',
  },
  'worthing': {
    formalName: 'Adur & Worthing Councils',
    department: 'Parking Services',
    addressLine1: 'Portland House, 44 Richmond Road',
    city: 'Worthing',
    postcode: 'BN11 1HS',
  },
  'wychavon': {
    formalName: 'Wychavon District Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre',
    addressLine2: 'Queen Elizabeth Drive',
    city: 'Pershore',
    postcode: 'WR10 1PT',
  },
  'wycombe': {
    formalName: 'Buckinghamshire Council',
    department: 'Parking Services Team',
    addressLine1: 'Walton Street Office',
    addressLine2: 'Walton Street',
    city: 'Aylesbury',
    postcode: 'HP20 1UA',
  },
  'wyre': {
    formalName: 'Wyre Council',
    department: 'Parking Services',
    addressLine1: 'Civic Centre, Breck Road',
    city: 'Poulton-le-Fylde',
    postcode: 'FY6 7PU',
  },
  'wyre-forest': {
    formalName: 'Wyre Forest District Council',
    department: 'Parking Services',
    addressLine1: 'Wyre Forest House',
    addressLine2: 'Finepoint Way',
    city: 'Kidderminster',
    postcode: 'DY11 7WF',
  },
  'york': {
    formalName: 'City of York Council',
    department: 'Parking Services',
    addressLine1: 'West Offices, Station Rise',
    city: 'York',
    postcode: 'YO1 6GA',
  },
  // Private Parking Companies
  'euro-car-parks': {
    formalName: 'Euro Car Parks (UK) Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 500',
    city: 'Leeds',
    postcode: 'LS1 1AZ',
  },
  'smart-parking': {
    formalName: 'Smart Parking Limited',
    department: 'Appeals Department',
    addressLine1: '4th Floor, The Shard',
    addressLine2: '32 London Bridge Street',
    city: 'London',
    postcode: 'SE1 9SG',
  },
  'apcoa-parking': {
    formalName: 'APCOA Parking (UK) Ltd',
    department: 'Appeals Department',
    addressLine1: 'Regus House',
    addressLine2: 'Windmill Hill Business Park, Whitehill Way',
    city: 'Swindon',
    postcode: 'SN5 6QR',
  },
  'ncp': {
    formalName: 'National Car Parks Limited',
    department: 'Customer Services',
    addressLine1: 'The Pinnacle',
    addressLine2: '20 Tudor Road',
    city: 'Reading',
    postcode: 'RG1 1NH',
  },
  'q-park': {
    formalName: 'Q-Park Limited',
    department: 'Customer Services',
    addressLine1: 'One Piccadilly Gardens',
    city: 'Manchester',
    postcode: 'M1 1RG',
  },
  'indigo-park': {
    formalName: 'Indigo Park Solutions UK Ltd',
    department: 'Appeals Department',
    addressLine1: 'Park Place, 10 Hatchery Close',
    city: 'Crawley',
    postcode: 'RH10 9AX',
  },
  'excel-parking-services': {
    formalName: 'Excel Parking Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'Sandringham House',
    addressLine2: '1 Sandringham Way',
    city: 'Rotherham',
    postcode: 'S63 7EH',
  },
  'parking-control-management': {
    formalName: 'Parking Control Management (PCM) Ltd',
    department: 'Appeals Department',
    addressLine1: '3 Ivy Business Centre',
    addressLine2: 'Crown Street',
    city: 'Failsworth',
    postcode: 'M35 9BG',
  },
  'vehicle-control-services': {
    formalName: 'Vehicle Control Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 2, Red Hall Court',
    addressLine2: 'Red Hall Lane',
    city: 'Wakefield',
    postcode: 'WF1 2UN',
  },
  'uk-parking-control': {
    formalName: 'UK Parking Control Ltd',
    department: 'Appeals Department',
    addressLine1: 'Eagle Court',
    addressLine2: '2 Hatchford Brook Road',
    city: 'Solihull',
    postcode: 'B92 0EG',
  },
  'civil-enforcement-ltd': {
    formalName: 'Civil Enforcement Ltd',
    department: 'Appeals Department',
    addressLine1: '200 Dukes Ride',
    city: 'Crowthorne',
    postcode: 'RG45 6DS',
  },
  'cp-plus': {
    formalName: 'CP Plus Ltd',
    department: 'Appeals Department',
    addressLine1: '4th Floor, Exchange Tower',
    addressLine2: '1 Harbour Exchange Square',
    city: 'London',
    postcode: 'E14 9GE',
  },
  'saba-parking': {
    formalName: 'Saba Park Services UK Ltd',
    department: 'Customer Services',
    addressLine1: 'Part First Floor, Osprey House',
    addressLine2: 'Ore Close, Lymedale Business Park',
    city: 'Newcastle-under-Lyme',
    postcode: 'ST5 9QD',
  },
  'town-centre-parking': {
    formalName: 'Town Centre Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'Freepost RTSE-UKZG-TYGA',
    city: 'London',
    postcode: 'EC1A 1AH',
  },
  'britannia-parking': {
    formalName: 'Britannia Parking Group Ltd',
    department: 'Appeals Department',
    addressLine1: '78 Chamber Road',
    city: 'Oldham',
    postcode: 'OL8 4AJ',
  },
  'gemini-parking-solutions': {
    formalName: 'Gemini Parking Solutions Ltd',
    department: 'Appeals Department',
    addressLine1: '1st Floor, Oakland House',
    addressLine2: 'Talbot Road',
    city: 'Manchester',
    postcode: 'M16 0PQ',
  },
  'athena-anpr': {
    formalName: 'Athena ANPR Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 4 Apex Business Village',
    addressLine2: 'Annitsford',
    city: 'Cramlington',
    postcode: 'NE23 7BF',
  },
  'alliance-parking-management': {
    formalName: 'Alliance Parking Management Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 17282',
    city: 'Birmingham',
    postcode: 'B2 2AN',
  },
  'premier-park': {
    formalName: 'Premier Park Ltd',
    department: 'Appeals Department',
    addressLine1: 'Premier House',
    addressLine2: 'Centric Close',
    city: 'Scunthorpe',
    postcode: 'DN15 8GR',
  },
  'one-parking': {
    formalName: 'One Parking Solution Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 5, Brookfield Business Park',
    city: 'Northampton',
    postcode: 'NN3 8EL',
  },
  'g24': {
    formalName: 'G24 Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 903',
    city: 'Crawley',
    postcode: 'RH10 0NN',
  },
  'ctl-parking': {
    formalName: 'CTL Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 17 Follingsby Close',
    city: 'Gateshead',
    postcode: 'NE10 8YG',
  },
  'highview-parking': {
    formalName: 'Highview Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'Sherwood House',
    addressLine2: '7 Gregory Boulevard',
    city: 'Nottingham',
    postcode: 'NG7 6LB',
  },
  'nationwide-parking-enforcement': {
    formalName: 'Nationwide Parking Enforcement Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 4, 1 Millers Way',
    city: 'Middleton',
    postcode: 'M24 2SS',
  },
  'met-parking-services': {
    formalName: 'Met Parking Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 744',
    city: 'Harrow',
    postcode: 'HA1 9WQ',
  },
  'new-generation-parking': {
    formalName: 'New Generation Parking Management Ltd',
    department: 'Appeals Department',
    addressLine1: 'Focus 31',
    addressLine2: 'Mark Road',
    city: 'Hemel Hempstead',
    postcode: 'HP2 7BW',
  },
  'park-watch': {
    formalName: 'Park Watch Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 1212',
    city: 'Sheffield',
    postcode: 'S1 9EP',
  },
  'armtrac': {
    formalName: 'Armtrac Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 3, Rowan Business Park',
    city: 'Heanor',
    postcode: 'DE75 7SL',
  },
  'swift-parking-services': {
    formalName: 'Swift Parking Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'Suite 3, The Courtyard',
    city: 'Lichfield',
    postcode: 'WS13 6QG',
  },
  'eagle-parking': {
    formalName: 'Eagle Parking Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'Eagle House',
    city: 'Basildon',
    postcode: 'SS14 3EZ',
  },
  'resolute-parking': {
    formalName: 'Resolute Parking Management Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 527',
    city: 'Purley',
    postcode: 'CR8 9EL',
  },
  'citrus-parking': {
    formalName: 'Citrus Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 7084',
    city: 'Leicester',
    postcode: 'LE1 6ZG',
  },
  'northern-parking-services': {
    formalName: 'Northern Parking Services Ltd',
    department: 'Appeals Department',
    addressLine1: '3 Brown Street',
    city: 'Manchester',
    postcode: 'M2 1DA',
  },
  'flash-park': {
    formalName: 'Flash Park Ltd',
    department: 'Appeals Department',
    addressLine1: '48 Warwick Street',
    city: 'London',
    postcode: 'W1B 5AW',
  },
  'parkmaven': {
    formalName: 'ParkMaven Ltd',
    department: 'Appeals Department',
    addressLine1: '20 Red Lion Street',
    city: 'London',
    postcode: 'WC1R 4PQ',
  },
  'cambridgeshire-parking-enforcement': {
    formalName: 'Cambridgeshire Parking Enforcement Ltd',
    department: 'Appeals Department',
    addressLine1: 'Suites 7-8 Manor Farm Barns',
    city: 'Cambridge',
    postcode: 'CB23 2TN',
  },
  'council-responsible-parking': {
    formalName: 'Council Responsible Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 1350',
    city: 'Bristol',
    postcode: 'BS99 7JY',
  },
  'patrol-parking': {
    formalName: 'Patrol Parking Ltd',
    department: 'Appeals Department',
    addressLine1: '6-8 City Road',
    city: 'London',
    postcode: 'EC1Y 2AA',
  },
  'all-parking-services': {
    formalName: 'All Parking Services Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 886',
    city: 'Stockport',
    postcode: 'SK1 9AW',
  },
  'apg-parking': {
    formalName: 'APG Parking Management Ltd',
    department: 'Appeals Department',
    addressLine1: 'Suite 12, Anglo Terrace',
    city: 'Bath',
    postcode: 'BA1 5AU',
  },
  'creative-car-park': {
    formalName: 'Creative Car Park Ltd',
    department: 'Appeals Department',
    addressLine1: '27 Old Gloucester Street',
    city: 'London',
    postcode: 'WC1N 3AX',
  },
  'ace-parking': {
    formalName: 'Ace Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 1, St James Trade Park',
    city: 'Southampton',
    postcode: 'SO14 5EB',
  },
  'zenith-parking': {
    formalName: 'Zenith Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 472',
    city: 'Nottingham',
    postcode: 'NG2 3DW',
  },
  'link-parking': {
    formalName: 'Link Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'Unit 1, Kings Court',
    addressLine2: 'Railway Street',
    city: 'Stafford',
    postcode: 'ST16 2LQ',
  },
  'moto-parking': {
    formalName: 'Moto Hospitality Ltd',
    department: 'Parking Appeals',
    addressLine1: 'Toddington Services',
    addressLine2: 'Junction 11/12 M1',
    city: 'Dunstable',
    postcode: 'LU5 6HR',
  },
  'orbit-parking': {
    formalName: 'Orbit Parking Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 2010',
    city: 'Worthing',
    postcode: 'BN11 9JT',
  },
  'minster-baywatch': {
    formalName: 'Minster Baywatch Ltd',
    department: 'Appeals Department',
    addressLine1: '26 High Street',
    city: 'Wimborne',
    postcode: 'BH21 1HU',
  },
  'north-west-parking-enforcement': {
    formalName: 'North West Parking Enforcement Ltd',
    department: 'Appeals Department',
    addressLine1: 'PO Box 400',
    city: 'Preston',
    postcode: 'PR1 1WR',
  },
};
