const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Expo config plugin that enables modular headers (module maps) for the
 * specific Objective-C pods that the AdMob / AppCheck Swift pods need to
 * `import` from Swift when built as static libraries.
 *
 * Why: react-native-google-mobile-ads pulls in GoogleUserMessagingPlatform,
 * which depends on the Swift pod `AppCheckCore`. `AppCheckCore` in turn
 * depends on the Objective-C pods `GoogleUtilities` and `RecaptchaInterop`,
 * which do NOT generate module maps by default. When AdMob is linked as a
 * static framework (see ./plugins/withAdMobStaticFramework), CocoaPods cannot
 * integrate the Swift pod against those module-less ObjC deps and aborts with:
 *
 *   [!] The following Swift pods cannot yet be integrated as static libraries:
 *   The Swift pod `AppCheckCore` depends upon `GoogleUtilities` and
 *   `RecaptchaInterop`, which do not define modules. To opt into those targets
 *   generating module maps ... you may set `use_modular_headers!` globally in
 *   your Podfile, or specify `:modular_headers => true` for particular
 *   dependencies.
 *
 * We take the surgical route the error suggests: enable modular headers for
 * just those two pods (plus AppCheckCore itself), rather than flipping
 * `use_modular_headers!` globally — global modular headers under SDK 56 /
 * RN 0.85 can break header visibility for unrelated pods, the same class of
 * problem that made us avoid global static frameworks (see
 * withAdMobStaticFramework). Per-pod `:modular_headers => true` keeps the blast
 * radius to the Google/AdMob dependency chain.
 *
 * The Podfile generated by Expo does not declare these transitive pods
 * explicitly, so we inject `pod '<name>', :modular_headers => true` lines
 * inside the main target. CocoaPods merges these with the autolinked
 * dependency graph and applies modular headers to the named pods.
 *
 * Usage in app.config.ts:
 *   plugins: ["./plugins/withModularHeaders"]
 *
 * Must run alongside ./plugins/withAdMobStaticFramework.
 */

// Pods that need module maps for the AppCheckCore Swift pod to integrate as a
// static library. AppCheckCore is listed too so its own module is generated.
const MODULAR_PODS = ["GoogleUtilities", "RecaptchaInterop", "AppCheckCore"];

const MARKER = "# withModularHeaders: modular header pods";

function withModularHeaders(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfilePath = path.join(
        cfg.modRequest.platformProjectRoot,
        "Podfile",
      );
      if (!fs.existsSync(podfilePath)) {
        return cfg;
      }

      let contents = fs.readFileSync(podfilePath, "utf8");
      if (contents.includes(MARKER)) {
        // Already injected (idempotent across repeated prebuilds).
        return cfg;
      }

      const podLines = MODULAR_PODS.map(
        (name) => `  pod '${name}', :modular_headers => true`,
      ).join("\n");
      const block = `\n  ${MARKER}\n${podLines}\n`;

      // Insert immediately after `use_expo_modules!` inside the target block.
      // That call is the first statement in the generated target, so anchoring
      // there reliably lands our pod declarations inside the target's do-block.
      const anchor = "use_expo_modules!";
      const anchorIndex = contents.indexOf(anchor);
      if (anchorIndex === -1) {
        throw new Error(
          "[withModularHeaders] Could not find `use_expo_modules!` in the " +
            "generated Podfile to anchor modular-header pod declarations.",
        );
      }

      const insertAt = anchorIndex + anchor.length;
      contents =
        contents.slice(0, insertAt) + "\n" + block + contents.slice(insertAt);

      fs.writeFileSync(podfilePath, contents);
      return cfg;
    },
  ]);
}

module.exports = withModularHeaders;
