import { useState } from 'react';
import { View, Text, Modal, ScrollView, Pressable } from 'react-native';
import { Image } from 'expo-image';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import {
  faEnvelope,
  faXmark,
  faExpand,
  faImage,
} from '@fortawesome/pro-solid-svg-icons';
import { Letter, LetterType } from '@/types';
import SquishyPressable from '@/components/SquishyPressable/SquishyPressable';

const LETTER_TYPE_LABELS: Record<string, string> = {
  [LetterType.INITIAL_NOTICE]: 'Initial Notice',
  [LetterType.NOTICE_TO_OWNER]: 'Notice to Owner (NTO)',
  [LetterType.CHARGE_CERTIFICATE]: 'Charge Certificate',
  [LetterType.ORDER_FOR_RECOVERY]: 'Order for Recovery',
  [LetterType.CCJ_NOTICE]: 'County Court Judgment (CCJ)',
  [LetterType.FINAL_DEMAND]: 'Final Demand',
  [LetterType.BAILIFF_NOTICE]: 'Bailiff Notice',
  [LetterType.APPEAL_RESPONSE]: 'Appeal Response',
  [LetterType.APPEAL_ACCEPTED]: 'Appeal Accepted',
  [LetterType.CHALLENGE_REJECTED]: 'Challenge Rejected',
  [LetterType.APPEAL_REJECTED]: 'Appeal Rejected',
  [LetterType.TE_FORM_RESPONSE]: 'Revoking Order (TE7/TE9)',
  [LetterType.PE_FORM_RESPONSE]: 'Revoking Order (PE2/PE3)',
  [LetterType.GENERIC]: 'Other Letter',
  [LetterType.CHALLENGE_LETTER]: 'Challenge Letter',
};

const formatDate = (date: string) => {
  const d = new Date(date);
  return d.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
};

const isImageUrl = (url: string) => /\.(jpeg|jpg|gif|png|webp)$/i.test(url);

type LettersReceivedCardProps = {
  letters: Letter[];
  onImagePress?: (imageUrl: string) => void;
};

export default function LettersReceivedCard({
  letters,
  onImagePress,
}: LettersReceivedCardProps) {
  const [selectedLetter, setSelectedLetter] = useState<Letter | null>(null);

  // Filter out challenge letters (those are generated by us, not received)
  const receivedLetters = letters.filter(
    (l) => l.type !== LetterType.CHALLENGE_LETTER,
  );

  if (receivedLetters.length === 0) return null;

  return (
    <>
      <View className="rounded-2xl border border-border bg-white p-4 mb-4">
        <View className="flex-row items-center mb-4">
          <Text className="font-jakarta-semibold text-lg text-dark">
            Letters Received
          </Text>
        </View>

        <View style={{ gap: 12 }}>
          {receivedLetters.map((letter) => {
            const letterImages =
              letter.media?.filter((m) => isImageUrl(m.url)) ?? [];

            return (
              <SquishyPressable
                key={letter.id}
                onPress={() => setSelectedLetter(letter)}
              >
                <View className="rounded-xl border border-border bg-light/50 p-3">
                  {/* Header row */}
                  <View className="flex-row items-start" style={{ gap: 10 }}>
                    <View
                      className="rounded-lg items-center justify-center"
                      style={{
                        width: 40,
                        height: 40,
                        backgroundColor: 'rgba(26, 188, 156, 0.1)',
                      }}
                    >
                      <FontAwesomeIcon
                        icon={faEnvelope}
                        size={18}
                        color="#1abc9c"
                      />
                    </View>
                    <View className="flex-1">
                      <Text className="font-jakarta-medium text-dark">
                        {LETTER_TYPE_LABELS[letter.type] || letter.type}
                      </Text>
                      <Text className="font-jakarta text-xs text-gray">
                        Received {formatDate(letter.sentAt)}
                      </Text>
                    </View>
                  </View>

                  {/* Summary preview */}
                  {letter.summary && (
                    <Text
                      className="font-jakarta text-sm text-dark/70 mt-2"
                      numberOfLines={2}
                    >
                      {letter.summary}
                    </Text>
                  )}

                  {/* Image thumbnail row */}
                  {letterImages.length > 0 && (
                    <View className="mt-3 flex-row items-center" style={{ gap: 8 }}>
                      <SquishyPressable
                        onPress={() => onImagePress?.(letterImages[0].url)}
                      >
                        <View className="relative">
                          <Image
                            source={{ uri: letterImages[0].url }}
                            style={{
                              width: 60,
                              height: 60,
                              borderRadius: 8,
                            }}
                            contentFit="cover"
                          />
                          <View
                            className="absolute items-center justify-center rounded-lg"
                            style={{
                              top: 0,
                              left: 0,
                              right: 0,
                              bottom: 0,
                              backgroundColor: 'rgba(0,0,0,0.2)',
                              borderRadius: 8,
                            }}
                          >
                            <FontAwesomeIcon
                              icon={faExpand}
                              size={14}
                              color="#ffffff"
                            />
                          </View>
                        </View>
                      </SquishyPressable>
                      <Text className="font-jakarta text-xs text-gray">
                        Tap thumbnail to view full image
                      </Text>
                    </View>
                  )}
                </View>
              </SquishyPressable>
            );
          })}
        </View>
      </View>

      {/* Letter Detail Modal */}
      <Modal
        visible={selectedLetter !== null}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setSelectedLetter(null)}
      >
        {selectedLetter && (
          <LetterDetailView
            letter={selectedLetter}
            onClose={() => setSelectedLetter(null)}
            onImagePress={onImagePress}
          />
        )}
      </Modal>
    </>
  );
}

function LetterDetailView({
  letter,
  onClose,
  onImagePress,
}: {
  letter: Letter;
  onClose: () => void;
  onImagePress?: (imageUrl: string) => void;
}) {
  const letterImages = letter.media?.filter((m) => isImageUrl(m.url)) ?? [];

  return (
    <View className="flex-1 bg-white">
      {/* Header */}
      <View className="flex-row items-center justify-between border-b border-border px-4 py-4">
        <View className="flex-row items-center" style={{ gap: 12 }}>
          <View
            className="rounded-lg items-center justify-center"
            style={{
              width: 40,
              height: 40,
              backgroundColor: 'rgba(26, 188, 156, 0.1)',
            }}
          >
            <FontAwesomeIcon icon={faEnvelope} size={18} color="#1abc9c" />
          </View>
          <View>
            <Text className="font-jakarta-semibold text-dark">
              {LETTER_TYPE_LABELS[letter.type] || letter.type}
            </Text>
            <Text className="font-jakarta text-xs text-gray">
              Received {formatDate(letter.sentAt)}
            </Text>
          </View>
        </View>
        <Pressable
          onPress={onClose}
          hitSlop={12}
          style={{
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: '#f3f4f6',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <FontAwesomeIcon icon={faXmark} size={16} color="#717171" />
        </Pressable>
      </View>

      <ScrollView className="flex-1 px-4 py-4">
        {/* Letter image */}
        {letterImages.length > 0 && (
          <View className="mb-4">
            <Text className="font-jakarta-medium text-xs text-gray mb-2">
              Original Image
            </Text>
            <SquishyPressable
              onPress={() => onImagePress?.(letterImages[0].url)}
            >
              <View className="relative">
                <Image
                  source={{ uri: letterImages[0].url }}
                  style={{
                    width: '100%',
                    height: 200,
                    borderRadius: 12,
                  }}
                  contentFit="cover"
                />
                <View
                  className="absolute items-center justify-center"
                  style={{
                    bottom: 8,
                    right: 8,
                    width: 36,
                    height: 36,
                    borderRadius: 18,
                    backgroundColor: 'rgba(0,0,0,0.5)',
                  }}
                >
                  <FontAwesomeIcon icon={faExpand} size={16} color="#ffffff" />
                </View>
              </View>
            </SquishyPressable>
          </View>
        )}

        {/* Summary */}
        {letter.summary && (
          <View className="mb-4">
            <Text className="font-jakarta-medium text-xs text-gray mb-2">
              Summary
            </Text>
            <Text className="font-jakarta text-sm text-dark leading-5">
              {letter.summary}
            </Text>
          </View>
        )}

        {/* Extracted content */}
        {letter.extractedText && (
          <View className="mb-4">
            <Text className="font-jakarta-medium text-xs text-gray mb-2">
              Extracted Content
            </Text>
            <View className="rounded-xl bg-light p-4">
              <Text className="font-mono text-xs text-dark/70 leading-5">
                {letter.extractedText}
              </Text>
            </View>
          </View>
        )}

        {/* No content fallback */}
        {!letter.summary && !letter.extractedText && (
          <View className="rounded-xl bg-light/50 py-8 items-center">
            <FontAwesomeIcon icon={faImage} size={28} color="#D1D5DB" />
            <Text className="font-jakarta text-sm text-gray mt-2">
              No text content was extracted from this letter.
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}
