import { useState } from 'react';
import { View, Text } from 'react-native';
import { Image } from 'expo-image';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { faEnvelope, faChevronDown, faChevronUp } from '@fortawesome/pro-solid-svg-icons';
import { Letter, LetterType } from '@/types';
import SquishyPressable from '@/components/SquishyPressable/SquishyPressable';

const LETTER_TYPE_LABELS: Record<string, string> = {
  [LetterType.INITIAL_NOTICE]: 'Initial Notice',
  [LetterType.NOTICE_TO_OWNER]: 'Notice to Owner (NTO)',
  [LetterType.CHARGE_CERTIFICATE]: 'Charge Certificate',
  [LetterType.ORDER_FOR_RECOVERY]: 'Order for Recovery',
  [LetterType.CCJ_NOTICE]: 'County Court Judgment (CCJ)',
  [LetterType.FINAL_DEMAND]: 'Final Demand',
  [LetterType.BAILIFF_NOTICE]: 'Bailiff Notice',
  [LetterType.APPEAL_RESPONSE]: 'Appeal Response',
  [LetterType.APPEAL_ACCEPTED]: 'Appeal Accepted',
  [LetterType.APPEAL_REJECTED]: 'Appeal Rejected',
  [LetterType.TE_FORM_RESPONSE]: 'Revoking Order (TE7/TE9)',
  [LetterType.PE_FORM_RESPONSE]: 'Revoking Order (PE2/PE3)',
  [LetterType.GENERIC]: 'Other Letter',
  [LetterType.CHALLENGE_LETTER]: 'Challenge Letter',
};

const formatDate = (date: string) => {
  const d = new Date(date);
  return d.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
};

const isImageUrl = (url: string) => /\.(jpeg|jpg|gif|png|webp)$/i.test(url);

type LettersReceivedCardProps = {
  letters: Letter[];
  onImagePress?: (imageUrl: string) => void;
};

export default function LettersReceivedCard({
  letters,
  onImagePress,
}: LettersReceivedCardProps) {
  const [expandedLetterId, setExpandedLetterId] = useState<string | null>(null);

  // Filter out challenge letters (those are generated by us, not received)
  const receivedLetters = letters.filter(
    (l) => l.type !== LetterType.CHALLENGE_LETTER,
  );

  if (receivedLetters.length === 0) return null;

  return (
    <View className="rounded-2xl border border-border bg-white p-4 mb-4">
      <View className="flex-row items-center mb-4">
        <Text className="font-jakarta-semibold text-lg text-dark">
          Letters Received
        </Text>
      </View>

      <View style={{ gap: 12 }}>
        {receivedLetters.map((letter) => {
          const isExpanded = expandedLetterId === letter.id;
          const letterImages = letter.media?.filter((m) =>
            isImageUrl(m.url),
          ) ?? [];

          return (
            <View
              key={letter.id}
              className="rounded-xl border border-border bg-light/50 p-3"
            >
              {/* Header row */}
              <View className="flex-row items-start" style={{ gap: 10 }}>
                <View
                  className="rounded-lg items-center justify-center"
                  style={{
                    width: 40,
                    height: 40,
                    backgroundColor: 'rgba(26, 188, 156, 0.1)',
                  }}
                >
                  <FontAwesomeIcon
                    icon={faEnvelope}
                    size={18}
                    color="#1abc9c"
                  />
                </View>
                <View className="flex-1">
                  <Text className="font-jakarta-medium text-dark">
                    {LETTER_TYPE_LABELS[letter.type] || letter.type}
                  </Text>
                  <Text className="font-jakarta text-xs text-gray">
                    Received {formatDate(letter.sentAt)}
                  </Text>
                </View>
              </View>

              {/* Letter image thumbnail */}
              {letterImages.length > 0 && (
                <View className="mt-3">
                  <SquishyPressable
                    onPress={() => onImagePress?.(letterImages[0].url)}
                  >
                    <Image
                      source={{ uri: letterImages[0].url }}
                      style={{
                        width: '100%',
                        height: 120,
                        borderRadius: 8,
                      }}
                      contentFit="cover"
                    />
                  </SquishyPressable>
                </View>
              )}

              {/* Extracted text preview / expand */}
              {letter.extractedText && (
                <View className="mt-3">
                  <SquishyPressable
                    onPress={() =>
                      setExpandedLetterId(isExpanded ? null : letter.id)
                    }
                  >
                    <View className="flex-row items-center justify-between rounded-lg bg-white p-3">
                      <Text className="font-jakarta-medium text-xs text-teal">
                        {isExpanded ? 'Hide Content' : 'View Content'}
                      </Text>
                      <FontAwesomeIcon
                        icon={isExpanded ? faChevronUp : faChevronDown}
                        size={12}
                        color="#1abc9c"
                      />
                    </View>
                  </SquishyPressable>

                  {isExpanded && (
                    <View className="mt-2 rounded-lg bg-white p-3">
                      <Text className="font-jakarta text-sm text-dark/80 leading-5">
                        {letter.extractedText}
                      </Text>
                    </View>
                  )}
                </View>
              )}
            </View>
          );
        })}
      </View>
    </View>
  );
}
